#!/usr/bin/env bash
# agent-size-audit.sh — SE-038 Slice 1 probe: measure size of every agent.
#
# Rule #22 enforces <4KB per agent definition in `.claude/agents/*.md` to
# keep agent selection hot path light. This script scans all agents,
# reports bytes + approximate token count (chars ÷ 4), flags violations,
# and supports an opt-in `size_exception:` frontmatter field for cases
# with explicit justification.
#
# Ref: SE-038, Rule #22, ROADMAP.md §Tier 1.2
# Safety: `set -uo pipefail`. Read-only. No destructive ops.

set -uo pipefail

REPO_ROOT="${REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
AGENTS_DIR="$REPO_ROOT/.claude/agents"
OUTPUT_DIR="$REPO_ROOT/output"
DATE_STR="$(date +%Y%m%d)"
REPORT="$OUTPUT_DIR/agent-size-report-$DATE_STR.md"

SLA_BYTES=4096

usage() {
  cat <<EOF
Usage: $0 [--quiet]

  --quiet    Suppress stdout summary, write report only.

Exit code: 1 if any agent exceeds SLA without documented exception.

Output: $REPORT
EOF
}

QUIET=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --quiet) QUIET=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "ERROR: unknown arg '$1'" >&2; usage; exit 2 ;;
  esac
done

mkdir -p "$OUTPUT_DIR"

# Detect size_exception in frontmatter (first 20 lines).
has_exception() {
  head -20 "$1" 2>/dev/null | grep -qE '^size_exception:'
}

total=0
violations=0
exceptions=0
total_bytes=0
RESULTS=()

while IFS= read -r agent; do
  [[ -f "$agent" ]] || continue
  total=$((total+1))
  bytes=$(wc -c < "$agent")
  chars=$(wc -m < "$agent")
  tokens=$(( chars / 4 ))
  total_bytes=$(( total_bytes + bytes ))
  name=$(basename "$agent" .md)

  is_exception=0
  if has_exception "$agent"; then
    is_exception=1
    exceptions=$((exceptions+1))
  fi

  status="PASS"
  if [[ "$bytes" -gt "$SLA_BYTES" ]]; then
    if [[ "$is_exception" -eq 1 ]]; then
      status="EXCEPTION"
    else
      status="VIOLATION"
      violations=$((violations+1))
    fi
  fi

  RESULTS+=("$bytes|$tokens|$status|$name")
done < <(find "$AGENTS_DIR" -maxdepth 1 -type f -name '*.md' | sort)

SORTED=$(printf '%s\n' "${RESULTS[@]}" | sort -t'|' -k1 -n -r)

{
  echo "# Agent size audit — $DATE_STR"
  echo ""
  echo "- Agents scanned: $total"
  echo "- SLA: $SLA_BYTES bytes per agent (Rule #22)"
  echo "- Violations: $violations"
  echo "- Documented exceptions: $exceptions"
  echo "- Total catalog bytes: $total_bytes"
  if [[ "$total" -gt 0 ]]; then
    echo "- Average: $(( total_bytes / total )) bytes/agent"
  fi
  echo ""
  echo "## Ranking (by size, descending)"
  echo ""
  echo "| Agent | Bytes | ~Tokens | Status |"
  echo "|---|---|---|---|"
  echo "$SORTED" | while IFS='|' read -r bytes tokens status name; do
    echo "| \`$name\` | $bytes | $tokens | $status |"
  done
  echo ""
  echo "## Interpretation"
  echo ""
  if [[ "$violations" -eq 0 ]]; then
    echo "No Rule #22 violations. Catalog is within SLA. Slice 2 (remediation) can be aborted."
  else
    echo "$violations agent(s) exceed $SLA_BYTES bytes without documented exception. Prioritize remediation in SE-038 Slice 2:"
    echo ""
    echo "$SORTED" | while IFS='|' read -r bytes tokens status name; do
      if [[ "$status" == "VIOLATION" ]]; then
        echo "- \`$name\`: $bytes bytes (exceeds SLA by $(( bytes - SLA_BYTES )))"
      fi
    done
    echo ""
    echo "Remediation options per Rule #22 documentation:"
    echo "- Split into specialized sub-agents"
    echo "- Move prose to DOMAIN.md of related skill"
    echo "- Add \`size_exception: <motivo>\` in frontmatter (requires review)"
    echo "- Compress redundancy"
  fi
  echo ""
  echo "---"
  echo ""
  echo "Generated by scripts/agent-size-audit.sh — $DATE_STR"
} > "$REPORT"

if [[ "$QUIET" -eq 0 ]]; then
  echo "agent-size-audit: total=$total violations=$violations exceptions=$exceptions total_bytes=$total_bytes"
  echo "  report: ${REPORT#$REPO_ROOT/}"
fi

# Exit 1 on violations (for CI integration in SE-038 Slice 3).
if [[ "$violations" -gt 0 ]]; then
  exit 1
fi
exit 0
