#!/usr/bin/env bash
# audit-all-bats.sh — SE-039 Slice 1 probe: run test-auditor over all .bats.
#
# SPEC-055 auditor measures test quality per file (safety, negatives,
# edges, coverage, references). This script applies it to every `.bats`
# file in `tests/` and produces a ranking. Identifies the bottom decile
# that needs remediation in Slice 2.
#
# Ref: SE-039, SPEC-055, ROADMAP.md §Tier 1.3
# Safety: `set -uo pipefail`. Read-only. Bounded concurrency (MAX_PARALLEL=5
# per bounded-concurrency.md doctrine).

set -uo pipefail

REPO_ROOT="${REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
TESTS_DIR="$REPO_ROOT/tests"
AUDITOR="$REPO_ROOT/scripts/test-auditor.sh"
OUTPUT_DIR="$REPO_ROOT/output"
DATE_STR="$(date +%Y%m%d)"
REPORT="$OUTPUT_DIR/bats-audit-sweep-$DATE_STR.md"

MIN_SCORE=80
MAX_PARALLEL="${MAX_PARALLEL:-5}"

usage() {
  cat <<EOF
Usage: $0 [--min-score N] [--quiet]

  --min-score N  Minimum acceptable score (default $MIN_SCORE)
  --quiet        Suppress stdout, write report only

Output: $REPORT
EOF
}

QUIET=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --min-score) MIN_SCORE="$2"; shift 2 ;;
    --quiet) QUIET=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "ERROR: unknown arg '$1'" >&2; usage; exit 2 ;;
  esac
done

mkdir -p "$OUTPUT_DIR"

if [[ ! -x "$AUDITOR" ]]; then
  echo "ERROR: test-auditor not found or not executable: $AUDITOR" >&2
  exit 2
fi

# Temp dir for per-file scores.
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# Bounded concurrency per bounded-concurrency.md doctrine.
audit_one() {
  local f="$1"
  local name
  name=$(basename "$f")
  local score
  # Auditor emits JSON with "total": N field.
  score=$(bash "$AUDITOR" "$f" 2>/dev/null | grep -oE '"total":[[:space:]]*[0-9]+' | grep -oE '[0-9]+' | head -1)
  score="${score:-0}"
  echo "$score|$name" > "$WORK/$name.score"
}

total=0
while IFS= read -r f; do
  [[ -f "$f" ]] || continue
  total=$((total+1))
  audit_one "$f" &
  while [[ $(jobs -rp | wc -l) -ge $MAX_PARALLEL ]]; do
    wait -n 2>/dev/null || true
  done
done < <(find "$TESTS_DIR" -maxdepth 1 -type f -name '*.bats' | sort)
wait

# Collect results.
RESULTS=()
while IFS= read -r result; do
  RESULTS+=("$(cat "$result")")
done < <(find "$WORK" -name '*.score' | sort)

# Sort ascending (worst first).
SORTED=$(printf '%s\n' "${RESULTS[@]}" | sort -t'|' -k1 -n)

# Compute stats.
below=0
at_or_above=0
sum=0
while IFS='|' read -r score name; do
  [[ -z "$score" ]] && continue
  sum=$(( sum + score ))
  if [[ "$score" -lt "$MIN_SCORE" ]]; then
    below=$((below+1))
  else
    at_or_above=$((at_or_above+1))
  fi
done <<< "$SORTED"

avg=0
if [[ "$total" -gt 0 ]]; then
  avg=$(( sum / total ))
fi

compliant_pct=0
if [[ "$total" -gt 0 ]]; then
  compliant_pct=$(( at_or_above * 100 / total ))
fi

{
  echo "# BATS audit sweep — $DATE_STR"
  echo ""
  echo "- Tests scanned: $total"
  echo "- Min score threshold: $MIN_SCORE"
  echo "- Compliant (≥ $MIN_SCORE): $at_or_above ($compliant_pct%)"
  echo "- Below threshold: $below"
  echo "- Average score: $avg"
  echo ""
  echo "## Bottom decile (priority for SE-039 Slice 2 remediation)"
  echo ""
  echo "| Score | Test file |"
  echo "|---|---|"
  bottom_count=0
  bottom_target=$(( total / 10 ))
  [[ "$bottom_target" -lt 5 ]] && bottom_target=5
  while IFS='|' read -r score name; do
    [[ -z "$score" ]] && continue
    if [[ "$bottom_count" -lt "$bottom_target" ]]; then
      echo "| $score | \`$name\` |"
      bottom_count=$((bottom_count+1))
    fi
  done <<< "$SORTED"
  echo ""
  echo "## Full ranking (by score, ascending)"
  echo ""
  echo "| Score | Test file |"
  echo "|---|---|"
  while IFS='|' read -r score name; do
    [[ -z "$score" ]] && continue
    echo "| $score | \`$name\` |"
  done <<< "$SORTED"
  echo ""
  echo "## Interpretation"
  echo ""
  if [[ "$compliant_pct" -ge 95 ]]; then
    echo "Compliance $compliant_pct% ≥ 95% target. Slice 2 remediation is low priority; focus on SE-039 Slice 3 enforcement gate."
  else
    echo "Compliance $compliant_pct% < 95% target. Gap of $(( 95 - compliant_pct ))pp. Prioritize bottom $bottom_target tests in SE-039 Slice 2 using patterns from test-quality doctrine."
  fi
  echo ""
  echo "---"
  echo ""
  echo "Generated by scripts/audit-all-bats.sh — $DATE_STR"
} > "$REPORT"

if [[ "$QUIET" -eq 0 ]]; then
  echo "audit-all-bats: total=$total compliant=$at_or_above ($compliant_pct%) avg=$avg"
  echo "  report: ${REPORT#$REPO_ROOT/}"
fi

exit 0
