#!/usr/bin/env bash
set -uo pipefail

# compile-agent-index.sh — Compiled agent reference index for LLM routing
# SPEC-097: Single optimized file from 49 agent definitions.
# Inspired by Anvil (ppazosp/anvil) AGENTS.md pattern.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
AGENTS_DIR="$REPO_ROOT/.claude/agents"
OUTPUT_FILE="$REPO_ROOT/.claude/AGENTS-INDEX.md"
CATALOG_FILE="$REPO_ROOT/docs/rules/domain/agents-catalog.md"
MATRIX_FILE="$REPO_ROOT/docs/rules/domain/assignment-matrix.md"

# ── Usage ────────────────────────────────────────────────────────────────────
usage() {
  cat <<'EOF'
Usage: compile-agent-index.sh <command>

Commands:
  compile    Generate .claude/AGENTS-INDEX.md from agent definitions
  check      Verify index is fresh (exit 0 = fresh, exit 1 = stale)
  show       Display current index
  stats      Show agent count, model distribution, permission levels
EOF
  exit 1
}

# ── Helpers ──────────────────────────────────────────────────────────────────

# Extract frontmatter field from an agent .md file
extract_field() {
  local file="$1"
  local field="$2"
  # Read between --- markers, find field
  sed -n '/^---$/,/^---$/p' "$file" | grep -E "^${field}:" | head -1 | sed "s/^${field}:[[:space:]]*//" | tr -d '"' | tr -d "'"
}

# Compute hash of all source files
compute_source_hash() {
  local hash_input=""

  # Hash all agent files
  if [[ -d "$AGENTS_DIR" ]]; then
    hash_input+=$(find "$AGENTS_DIR" -name "*.md" -type f | sort | xargs cat 2>/dev/null)
  fi

  # Hash catalog and matrix
  [[ -f "$CATALOG_FILE" ]] && hash_input+=$(cat "$CATALOG_FILE")
  [[ -f "$MATRIX_FILE" ]] && hash_input+=$(cat "$MATRIX_FILE")

  echo "$hash_input" | sha256sum | cut -d' ' -f1
}

# ── Commands ─────────────────────────────────────────────────────────────────

cmd_compile() {
  local source_hash
  source_hash=$(compute_source_hash)
  local timestamp
  timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  local agent_count=0

  {
    cat <<HEADER
# Agent Index — pm-workspace (compiled)

> Auto-generated by compile-agent-index.sh. Do not edit manually.
> Hash: ${source_hash}
> Generated: ${timestamp}

## Quick Routing (task → agent)

| Task type | Agent | Model | Budget |
|-----------|-------|-------|--------|
HEADER

    # Parse assignment matrix for quick routing
    if [[ -f "$MATRIX_FILE" ]]; then
      grep -E '^\|.*\|.*\|.*\|.*\|$' "$MATRIX_FILE" \
        | grep -vE '^\|[- ]+\|' \
        | grep -vE '^\| Tipo' \
        | head -20 \
        | while IFS='|' read -r _ task agent backup qa _; do
            task=$(echo "$task" | xargs)
            agent=$(echo "$agent" | xargs)
            [[ -z "$task" || -z "$agent" ]] && continue
            # Look up model and budget from agent file
            local agent_file="$AGENTS_DIR/${agent}.md"
            local model="-"
            local budget="-"
            if [[ -f "$agent_file" ]]; then
              model=$(extract_field "$agent_file" "model")
              budget=$(extract_field "$agent_file" "token_budget")
              [[ -z "$model" ]] && model="-"
              [[ -z "$budget" ]] && budget="-"
            fi
            echo "| $task | $agent | $model | $budget |"
          done
    fi

    cat <<'FLOWS'

## Flows (ultra-compact)

```
SDD:      analyst → architect → spec-writer → developer ‖ tester → reviewer
Infra:    architect → infra-agent → human-approves → apply
Security: attacker → defender → auditor (static) | pentester → defender → auditor (dynamic)
Consensus: reflection + code-reviewer + business-analyst → weighted score
DevSession: orchestrator → developer → tester ‖ coherence → reviewer
Digest:   meeting-digest → confidentiality-judge → risk-analyst
```

## All Agents

| # | Agent | Model | Permission | Specialty |
|---|-------|-------|------------|-----------|
FLOWS

    # Parse all agent files
    local n=0
    for agent_file in "$AGENTS_DIR"/*.md; do
      [[ ! -f "$agent_file" ]] && continue
      n=$((n + 1))

      local name
      name=$(extract_field "$agent_file" "name")
      [[ -z "$name" ]] && name=$(basename "$agent_file" .md)

      local model
      model=$(extract_field "$agent_file" "model")
      [[ -z "$model" ]] && model="-"

      local perm
      perm=$(extract_field "$agent_file" "permission_level")
      [[ -z "$perm" ]] && perm="-"

      local desc
      desc=$(extract_field "$agent_file" "description")
      # Truncate description to 60 chars
      if [[ ${#desc} -gt 60 ]]; then
        desc="${desc:0:57}..."
      fi

      echo "| $n | $name | $model | $perm | $desc |"
    done

    agent_count=$n

    cat <<FOOTER

---
Agents: $agent_count | Hash: ${source_hash:0:12}... | Generated: $timestamp
FOOTER
  } > "$OUTPUT_FILE"

  echo "Compiled $agent_count agents → $OUTPUT_FILE"
  echo "Source hash: ${source_hash:0:12}..."
}

cmd_check() {
  if [[ ! -f "$OUTPUT_FILE" ]]; then
    echo "STALE: Index file does not exist"
    exit 1
  fi

  local current_hash
  current_hash=$(compute_source_hash)

  local stored_hash
  stored_hash=$(grep -oP 'Hash: \K[a-f0-9]+' "$OUTPUT_FILE" | head -1)

  if [[ "$current_hash" == "$stored_hash" ]]; then
    echo "FRESH: Index is up to date (hash: ${current_hash:0:12}...)"
    exit 0
  else
    echo "STALE: Sources changed since last compile"
    echo "  Current: ${current_hash:0:12}..."
    echo "  Stored:  ${stored_hash:0:12}..."
    exit 1
  fi
}

cmd_show() {
  if [[ -f "$OUTPUT_FILE" ]]; then
    cat "$OUTPUT_FILE"
  else
    echo "No index found. Run 'compile' first." >&2
    exit 1
  fi
}

cmd_stats() {
  if [[ ! -d "$AGENTS_DIR" ]]; then
    echo "No agents directory found at $AGENTS_DIR" >&2
    exit 1
  fi

  local total=0
  declare -A models
  declare -A perms

  for agent_file in "$AGENTS_DIR"/*.md; do
    [[ ! -f "$agent_file" ]] && continue
    total=$((total + 1))

    local model
    model=$(extract_field "$agent_file" "model")
    [[ -z "$model" ]] && model="unspecified"
    models[$model]=$(( ${models[$model]:-0} + 1 ))

    local perm
    perm=$(extract_field "$agent_file" "permission_level")
    [[ -z "$perm" ]] && perm="unspecified"
    perms[$perm]=$(( ${perms[$perm]:-0} + 1 ))
  done

  echo "Agent Statistics"
  echo "  Total agents: $total"
  echo ""
  echo "  By model:"
  for m in "${!models[@]}"; do
    echo "    $m: ${models[$m]}"
  done | sort
  echo ""
  echo "  By permission level:"
  for p in "${!perms[@]}"; do
    echo "    $p: ${perms[$p]}"
  done | sort

  if [[ -f "$OUTPUT_FILE" ]]; then
    echo ""
    echo "  Index: EXISTS ($(wc -l < "$OUTPUT_FILE") lines)"
    bash "$0" check 2>/dev/null && echo "  Freshness: FRESH" || echo "  Freshness: STALE"
  else
    echo ""
    echo "  Index: NOT COMPILED"
  fi
}

# ── Main ─────────────────────────────────────────────────────────────────────

[[ $# -lt 1 ]] && usage
CMD="$1"; shift

case "$CMD" in
  compile) cmd_compile ;;
  check)   cmd_check ;;
  show)    cmd_show ;;
  stats)   cmd_stats ;;
  *)
    echo "Unknown command: $CMD" >&2
    usage
    ;;
esac
