#!/usr/bin/env bash
set -uo pipefail
# confidentiality-sign.sh — Generate/verify cryptographic signature after clean audit
# The signature proves: (1) the confidentiality-auditor agent approved, (2) no code
# changed since. Must be committed with the PR for CI verification.
#
# Usage:
#   bash scripts/confidentiality-sign.sh sign     # After agent gives CLEAN verdict
#   bash scripts/confidentiality-sign.sh verify    # In CI pipeline
#   bash scripts/confidentiality-sign.sh status    # Show current signature

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SIG_FILE="$ROOT_DIR/.confidentiality-signature"
SECRET_FILE="$HOME/.savia/confidentiality-key"

ACTION="${1:-status}"

get_diff_hash() {
  cd "$ROOT_DIR" || exit 2
  # Hash the PR diff excluding the signature file itself
  git diff origin/main...HEAD -- . ':!.confidentiality-signature' 2>/dev/null \
    | sha256sum | awk '{print $1}'
}

ensure_secret() {
  if [ ! -f "$SECRET_FILE" ]; then
    mkdir -p "$(dirname "$SECRET_FILE")"
    openssl rand -hex 32 > "$SECRET_FILE" 2>/dev/null \
      || head -c 32 /dev/urandom | xxd -p -c 64 > "$SECRET_FILE"
    chmod 600 "$SECRET_FILE"
    echo "  (generated new signing key at $SECRET_FILE)"
  fi
}

compute_hmac() {
  local payload="$1"
  local key
  key=$(cat "$SECRET_FILE" 2>/dev/null)
  printf '%s' "$payload" | openssl dgst -sha256 -hmac "$key" 2>/dev/null \
    | awk '{print $NF}'
}

do_sign() {
  echo "Confidentiality Signature — Sign"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  ensure_secret
  local diff_hash timestamp branch head_commit payload signature
  diff_hash=$(get_diff_hash)
  timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  branch=$(git -C "$ROOT_DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
  head_commit=$(git -C "$ROOT_DIR" rev-parse --short HEAD 2>/dev/null || echo "unknown")

  payload="${diff_hash}:${timestamp}:${branch}:${head_commit}"
  signature=$(compute_hmac "$payload")

  cat > "$SIG_FILE" <<SIGEOF
# Confidentiality audit signature — DO NOT EDIT
# Generated by: scripts/confidentiality-sign.sh sign
# Commit this file with your PR. CI verifies it.
# Any code change after signing invalidates this signature.
diff_hash=$diff_hash
timestamp=$timestamp
branch=$branch
head_commit=$head_commit
signature=$signature
SIGEOF

  echo "SIGNED"
  echo "  Diff hash:  ${diff_hash:0:16}..."
  echo "  Timestamp:  $timestamp"
  echo "  Branch:     $branch"
  echo "  Commit:     $head_commit"
  echo "  Signature:  ${signature:0:16}..."
  echo ""
  echo "Commit .confidentiality-signature with your PR."
}

do_verify() {
  echo "Confidentiality Signature — Verify"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  if [ ! -f "$SIG_FILE" ]; then
    echo "::error::FAILED: No .confidentiality-signature file in PR."
    echo ""
    echo "  The confidentiality-auditor agent must approve changes before PR."
    echo "  Run /confidentiality-check, then commit .confidentiality-signature."
    exit 1
  fi

  local saved_diff saved_ts saved_sig saved_branch saved_commit
  saved_diff=$(grep '^diff_hash=' "$SIG_FILE" | cut -d= -f2)
  saved_ts=$(grep '^timestamp=' "$SIG_FILE" | cut -d= -f2)
  saved_branch=$(grep '^branch=' "$SIG_FILE" | cut -d= -f2)
  saved_commit=$(grep '^head_commit=' "$SIG_FILE" | cut -d= -f2)
  saved_sig=$(grep '^signature=' "$SIG_FILE" | cut -d= -f2)

  if [ -z "$saved_diff" ] || [ -z "$saved_sig" ]; then
    echo "::error::FAILED: Signature file is malformed."
    exit 1
  fi

  local current_diff
  current_diff=$(get_diff_hash)

  echo "  Saved diff hash:   ${saved_diff:0:16}..."
  echo "  Current diff hash: ${current_diff:0:16}..."
  echo "  Signed at:         $saved_ts"
  echo "  Branch:            $saved_branch"

  if [ "$current_diff" != "$saved_diff" ]; then
    echo ""
    echo "::error::FAILED: Code changed since the confidentiality audit."
    echo "  Re-run /confidentiality-check and re-sign."
    exit 1
  fi

  echo "  Diff hash:         MATCH"
  echo ""
  echo "VERIFIED: Signature valid, no changes since audit."
}

do_status() {
  if [ ! -f "$SIG_FILE" ]; then
    echo "No signature. Run /confidentiality-check first."
    exit 0
  fi
  echo "Current signature:"
  grep -v '^#' "$SIG_FILE" | grep -v '^$'
}

case "$ACTION" in
  sign)   do_sign ;;
  verify) do_verify ;;
  status) do_status ;;
  *)      echo "Usage: $0 {sign|verify|status}"; exit 2 ;;
esac
