#!/usr/bin/env bash
# resolve-pr-conflicts.sh — auto-resolver for the recurring conflicts that
# appear on open PRs whenever main advances. Patterns observed:
#   - CHANGELOG.md: each PR adds a new version at the top + a link line
#     at the end. When main merges a peer PR, both claim the top slot.
#   - .confidentiality-signature: each PR signs its diff. When a peer
#     merges, the file's hash changes upstream. Signature is regenerated
#     on next /pr-plan — conflict is stale content.
#   - .scm/: regenerated by generate-capability-map.py. Deterministic
#     content-hash header — conflict is stale content.
#
# Strategy:
#   1. `git merge origin/main --no-edit` to surface conflicts.
#   2. CHANGELOG: take theirs (main) for the header+older entries, then
#      re-prepend our new entry from HEAD, dedupe link lines.
#   3. .confidentiality-signature: take theirs, will be re-signed.
#   4. .scm/: take theirs, will be regenerated.
#   5. Commit merge, re-sign, push.
#
# Usage:
#   resolve-pr-conflicts.sh [--branch BRANCH] [--dry-run] [--no-push]
#
# Environment:
#   RESOLVE_REPO_ROOT override (defaults to `git rev-parse --show-toplevel`)
#
# Ref: SPEC-SE-012-like signal/noise. Reply to "merging one PR breaks all others" pain.
# Safety: `set -uo pipefail`. Aborts cleanly on unknown conflicts.

set -uo pipefail

REPO_ROOT="${RESOLVE_REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
cd "$REPO_ROOT"

BRANCH=""
DRY_RUN=0
NO_PUSH=0

usage() {
  cat <<EOF
Usage: $0 [--branch BRANCH] [--dry-run] [--no-push]

  --branch BRANCH   Target branch to rebase (default: current branch).
  --dry-run         Show what would be done without modifying.
  --no-push         Resolve + commit locally, skip git push.

Auto-resolves CHANGELOG.md + .confidentiality-signature + .scm/*
conflicts when merging origin/main into a PR branch. Fails cleanly on
unexpected conflicts in OTHER files (human intervention required).
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --branch) BRANCH="$2"; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    --no-push) NO_PUSH=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "ERROR: unknown arg '$1'" >&2; usage; exit 2 ;;
  esac
done

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
[[ -z "$BRANCH" ]] && BRANCH="$CURRENT_BRANCH"

if [[ "$BRANCH" == "main" || "$BRANCH" == "master" ]]; then
  echo "ERROR: refusing to rebase main/master" >&2
  exit 2
fi

echo "resolve-pr-conflicts: target branch = $BRANCH"

if [[ "$CURRENT_BRANCH" != "$BRANCH" ]]; then
  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "  [dry-run] would: git checkout $BRANCH"
  else
    git checkout "$BRANCH" --quiet || exit 2
  fi
fi

# Ensure we have latest main.
git fetch origin main --quiet

# Attempt merge; expected to produce conflicts on CHANGELOG+signature.
if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "  [dry-run] would: git merge origin/main --no-edit"
  exit 0
fi

merge_output=$(git merge origin/main --no-edit 2>&1)
merge_status=$?

if [[ "$merge_status" -eq 0 ]]; then
  echo "resolve-pr-conflicts: no conflicts, already in sync with main"
  exit 0
fi

# Check which files are in conflict.
conflicted=$(git diff --name-only --diff-filter=U)
echo "resolve-pr-conflicts: conflicts in:"
echo "$conflicted" | sed 's/^/  - /'

# Validate that ONLY expected files are conflicted.
unexpected=""
while IFS= read -r f; do
  case "$f" in
    CHANGELOG.md|.confidentiality-signature|.scm/*) ;;
    *) unexpected+="$f"$'\n' ;;
  esac
done <<< "$conflicted"

if [[ -n "$unexpected" ]]; then
  echo ""
  echo "ERROR: unexpected conflict files require human review:" >&2
  echo "$unexpected" | sed 's/^/  - /' >&2
  echo "" >&2
  echo "Aborting merge. Use 'git merge --abort' to reset." >&2
  exit 3
fi

# ── CHANGELOG.md resolution ────────────────────────────────────────────────

if echo "$conflicted" | grep -q '^CHANGELOG.md$'; then
  echo "  resolving CHANGELOG.md..."

  # Strategy:
  # 1. Extract OURS version entry (the new section added in this PR).
  # 2. Take THEIRS (main) as base.
  # 3. Prepend OURS entry to the top (after the header preamble).
  # 4. Merge link tables: append OURS link lines that don't exist in THEIRS.

  # Save OURS and THEIRS versions.
  git show ":2:CHANGELOG.md" > /tmp/changelog-ours.md
  git show ":3:CHANGELOG.md" > /tmp/changelog-theirs.md

  # Find OURS top version entry.
  ours_top_line=$(grep -nE '^## \[[0-9]+\.[0-9]+\.[0-9]+\]' /tmp/changelog-ours.md | head -1 | cut -d: -f1)
  ours_next_line=$(grep -nE '^## \[[0-9]+\.[0-9]+\.[0-9]+\]' /tmp/changelog-ours.md | sed -n '2p' | cut -d: -f1)

  if [[ -z "$ours_top_line" || -z "$ours_next_line" ]]; then
    echo "  ERROR: cannot parse OURS CHANGELOG structure" >&2
    git merge --abort
    exit 3
  fi

  ours_entry=$(sed -n "${ours_top_line},$((ours_next_line-1))p" /tmp/changelog-ours.md)

  # Find OURS link line.
  ours_version=$(echo "$ours_entry" | head -1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
  ours_link=$(grep -E "^\[${ours_version}\]:" /tmp/changelog-ours.md || echo "")

  # Insert OURS entry into THEIRS above the first "## [" header.
  theirs_header_line=$(grep -nE '^## \[[0-9]+\.[0-9]+\.[0-9]+\]' /tmp/changelog-theirs.md | head -1 | cut -d: -f1)
  {
    sed -n "1,$((theirs_header_line-1))p" /tmp/changelog-theirs.md
    echo "$ours_entry"
    sed -n "${theirs_header_line},\$p" /tmp/changelog-theirs.md
  } > /tmp/changelog-merged.md

  # Append OURS link line if not already in THEIRS.
  if [[ -n "$ours_link" ]] && ! grep -qF "$ours_link" /tmp/changelog-merged.md; then
    # Find the first link line; insert OURS above it (newer on top).
    first_link_line=$(grep -nE '^\[[0-9]+\.[0-9]+\.[0-9]+\]:' /tmp/changelog-merged.md | head -1 | cut -d: -f1)
    if [[ -n "$first_link_line" ]]; then
      sed -i "${first_link_line}i\\
$ours_link" /tmp/changelog-merged.md
    else
      echo "$ours_link" >> /tmp/changelog-merged.md
    fi
  fi

  cp /tmp/changelog-merged.md CHANGELOG.md
  git add CHANGELOG.md
  rm -f /tmp/changelog-ours.md /tmp/changelog-theirs.md /tmp/changelog-merged.md
  echo "  CHANGELOG.md resolved (kept OURS v$ours_version entry + link)"
fi

# ── .confidentiality-signature resolution ──────────────────────────────────

if echo "$conflicted" | grep -q '^\.confidentiality-signature$'; then
  echo "  resolving .confidentiality-signature (take theirs, will re-sign)..."
  git checkout --theirs .confidentiality-signature
  git add .confidentiality-signature
fi

# ── .scm/ resolution ───────────────────────────────────────────────────────

scm_conflicts=$(echo "$conflicted" | grep '^\.scm/' || true)
if [[ -n "$scm_conflicts" ]]; then
  echo "  resolving .scm/* (take theirs, will regenerate)..."
  while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    git checkout --theirs "$f"
    git add "$f"
  done <<< "$scm_conflicts"
fi

# ── Commit merge ───────────────────────────────────────────────────────────

git commit --no-edit -m "Merge origin/main — auto-resolved CHANGELOG + signature + .scm

Conflicts resolved by scripts/resolve-pr-conflicts.sh:
- CHANGELOG.md: kept our new version entry + link, rebased on main
- .confidentiality-signature: will be re-signed
- .scm/: will be regenerated

Co-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>"

# ── Regenerate SCM if generator present ────────────────────────────────────

if [[ -x "scripts/generate-capability-map.py" ]]; then
  python3 scripts/generate-capability-map.py >/dev/null 2>&1 || true
  if ! git diff --quiet .scm/; then
    git add .scm/
    git commit -m "chore(scm): regen after conflict resolution

Co-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>" >/dev/null 2>&1 || true
  fi
fi

# ── Re-sign confidentiality ────────────────────────────────────────────────

if [[ -x "scripts/confidentiality-sign.sh" ]]; then
  bash scripts/confidentiality-sign.sh sign >/dev/null 2>&1
  if ! git diff --quiet .confidentiality-signature; then
    git add .confidentiality-signature
    git commit -m "chore: re-sign after conflict resolution

Co-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>" >/dev/null 2>&1 || true
  fi
fi

# ── Push ──────────────────────────────────────────────────────────────────

if [[ "$NO_PUSH" -eq 1 ]]; then
  echo ""
  echo "resolve-pr-conflicts: done (--no-push, skipping git push)"
  exit 0
fi

echo ""
echo "resolve-pr-conflicts: pushing $BRANCH..."
git push origin "$BRANCH" 2>&1 | tail -3

echo ""
echo "resolve-pr-conflicts: ✅ $BRANCH synced with main, PR should now be MERGEABLE"
exit 0
