#!/usr/bin/env bash
set -uo pipefail
# savia-preferences.sh — manage ~/.savia/preferences.yaml (SPEC-127 Slice 1)
#
# Source-of-truth for the user's personal Savia stack: frontend, inference
# provider, model aliases, capability declarations, budget policy, auth shape.
# Per-user, never committed to the repo. The framework reads this file via
# scripts/savia-env.sh; commands read it via this script's `get` subcommand.
#
# Subcommands:
#   init                  Interactive onboarding (8 questions). Idempotent.
#   show                  Print current preferences.yaml (or "absent").
#   get <key>             Print scalar value for top-level key.
#   set <key> <value>     Set scalar value (creates file if absent).
#   reset                 Delete preferences.yaml (with --confirm).
#   validate              Verify schema against model-alias-schema.md.
#
# Reference: SPEC-127 Slice 1 AC-1.2
# Reference: docs/rules/domain/provider-agnostic-env.md
# Reference: docs/rules/domain/model-alias-schema.md

PREFS_DIR="${SAVIA_PREFS_DIR:-${HOME:-/tmp}/.savia}"
PREFS_FILE="${SAVIA_PREFS_FILE:-${PREFS_DIR}/preferences.yaml}"

usage() {
  cat <<USG
Usage: savia-preferences.sh <subcommand> [args]

Subcommands:
  init                  Interactive onboarding (8 questions)
  show                  Print current preferences.yaml
  get <key>             Get scalar value
  set <key> <value>     Set scalar value
  reset                 Delete preferences.yaml (requires --confirm)
  validate              Validate against schema

Files:
  ${PREFS_FILE}
USG
}

ensure_dir() {
  mkdir -p "$PREFS_DIR" 2>/dev/null || true
  if [[ ! -d "$PREFS_DIR" ]]; then
    echo "ERROR: cannot create $PREFS_DIR" >&2
    return 1
  fi
}

# Read a top-level scalar from preferences.yaml.
get_pref() {
  local key="$1"
  [[ -f "$PREFS_FILE" ]] || return 0
  awk -v k="^${key}:" '
    $0 ~ k {
      sub(k, ""); sub(/^[[:space:]]+/, "")
      gsub(/^"|"$/, ""); gsub(/^'\''|'\''$/, "")
      print
      exit
    }
  ' "$PREFS_FILE"
}

# Set a top-level scalar — replace existing or append.
set_pref() {
  local key="$1" value="$2"
  ensure_dir || return 1
  if [[ ! -f "$PREFS_FILE" ]]; then
    {
      echo "# Savia preferences — per-user, never committed."
      echo "# Generated by scripts/savia-preferences.sh (SPEC-127 Slice 1)."
      echo "version: 1"
    } > "$PREFS_FILE"
  fi
  if grep -qE "^${key}:" "$PREFS_FILE"; then
    # Replace
    local tmp
    tmp=$(mktemp)
    awk -v k="^${key}:" -v v="${key}: ${value}" '
      $0 ~ k { print v; next }
      { print }
    ' "$PREFS_FILE" > "$tmp"
    mv "$tmp" "$PREFS_FILE"
  else
    echo "${key}: ${value}" >> "$PREFS_FILE"
  fi
}

# Validation: check structural keys present, no obvious schema breaks.
validate() {
  if [[ ! -f "$PREFS_FILE" ]]; then
    echo "preferences absent — defaults will apply" >&2
    return 0
  fi
  local errors=0
  for required in version; do
    if ! grep -qE "^${required}:" "$PREFS_FILE"; then
      echo "MISSING required key: ${required}" >&2
      errors=$((errors + 1))
    fi
  done
  for forbidden in api_key password secret token; do
    if grep -qiE "^${forbidden}:" "$PREFS_FILE"; then
      echo "FORBIDDEN key in preferences (use a credential manager): ${forbidden}" >&2
      errors=$((errors + 1))
    fi
  done
  if [[ $errors -eq 0 ]]; then
    echo "preferences valid"
    return 0
  fi
  return 1
}

# Interactive onboarding — neutral 8-question flow. No vendor presets.
prompt_value() {
  local question="$1" default="${2:-}" var
  if [[ -n "$default" ]]; then
    printf '%s [%s]: ' "$question" "$default" >&2
  else
    printf '%s: ' "$question" >&2
  fi
  read -r var
  if [[ -z "$var" && -n "$default" ]]; then
    var="$default"
  fi
  echo "$var"
}

init() {
  ensure_dir || return 1
  if [[ -f "$PREFS_FILE" ]]; then
    printf 'Preferences exist at %s. Re-running will update keys (existing values shown as default).\n\n' "$PREFS_FILE" >&2
  else
    printf 'Welcome to Savia setup. 8 questions, all with free-form answers.\nNothing about your stack is committed to the repo.\n\n' >&2
  fi

  local frontend provider heavy mid fast has_hooks has_task has_slash budget_kind budget_limit auth_kind

  frontend=$(prompt_value "1/8 Frontend (claude-code / opencode / codex / cursor / other)" "$(get_pref frontend)")
  provider=$(prompt_value "2/8 Inference provider name (free text — vendor / 'localai' / 'ollama' / 'custom-corp' / etc.)" "$(get_pref provider)")
  heavy=$(prompt_value "3a/8 Preferred HEAVY-tier model (free text — vendor model id)" "$(get_pref model_heavy)")
  mid=$(prompt_value "3b/8 Preferred MID-tier model" "$(get_pref model_mid)")
  fast=$(prompt_value "3c/8 Preferred FAST-tier model" "$(get_pref model_fast)")
  has_hooks=$(prompt_value "4/8 Does your stack expose hook events (yes/no/autodetect)" "$(get_pref has_hooks)")
  has_task=$(prompt_value "5/8 Does your stack expose subagent fan-out / Task tool (yes/no/autodetect)" "$(get_pref has_task_fan_out)")
  has_slash=$(prompt_value "6/8 Does your stack expose slash commands (yes/no/autodetect)" "$(get_pref has_slash_commands)")
  budget_kind=$(prompt_value "7a/8 Budget kind (none / req-count / token-count / dollar-cap)" "$(get_pref budget_kind)")
  budget_limit=$(prompt_value "7b/8 Budget monthly limit (number, or empty if none)" "$(get_pref budget_limit)")
  auth_kind=$(prompt_value "8/8 Auth shape (none / api-key / oauth / mtls / corporate-custom)" "$(get_pref auth_kind)")

  [[ -n "$frontend"     ]] && set_pref frontend          "$frontend"
  [[ -n "$provider"     ]] && set_pref provider          "$provider"
  [[ -n "$heavy"        ]] && set_pref model_heavy       "$heavy"
  [[ -n "$mid"          ]] && set_pref model_mid         "$mid"
  [[ -n "$fast"         ]] && set_pref model_fast        "$fast"
  [[ -n "$has_hooks"    ]] && set_pref has_hooks         "$has_hooks"
  [[ -n "$has_task"     ]] && set_pref has_task_fan_out  "$has_task"
  [[ -n "$has_slash"    ]] && set_pref has_slash_commands "$has_slash"
  [[ -n "$budget_kind"  ]] && set_pref budget_kind       "$budget_kind"
  [[ -n "$budget_limit" ]] && set_pref budget_limit      "$budget_limit"
  [[ -n "$auth_kind"    ]] && set_pref auth_kind         "$auth_kind"

  printf '\nSaved to %s.\n' "$PREFS_FILE" >&2
  validate
}

show() {
  if [[ ! -f "$PREFS_FILE" ]]; then
    echo "preferences absent (file: $PREFS_FILE)"
    return 0
  fi
  cat "$PREFS_FILE"
}

reset() {
  if [[ "${1:-}" != "--confirm" ]]; then
    echo "ERROR: reset requires --confirm (irreversible)" >&2
    return 2
  fi
  if [[ -f "$PREFS_FILE" ]]; then
    rm -f "$PREFS_FILE"
    echo "preferences deleted"
  else
    echo "no preferences to delete"
  fi
}

case "${1:-}" in
  init)     init ;;
  show)     show ;;
  get)      shift; get_pref "${1:-}" ;;
  set)      shift; set_pref "${1:-}" "${2:-}" ;;
  reset)    shift; reset "${1:-}" ;;
  validate) validate ;;
  --help|-h|help) usage ;;
  *) echo "unknown subcommand: ${1:-(none)}" >&2; usage >&2; exit 2 ;;
esac
