#!/usr/bin/env python3
"""
savia-dual-proxy — Transparent failover proxy between Anthropic API and local Ollama.

Part of Savia Dual (pm-workspace). Listens on 127.0.0.1:8787 by default.
Claude Code talks to this proxy via ANTHROPIC_BASE_URL. The proxy tries the
primary upstream (Anthropic) first; on failure (network, 5xx, 429, timeout)
it transparently falls back to a local Ollama instance speaking the native
Anthropic /v1/messages protocol (Ollama >= 0.20.0).

Zero external dependencies. Stdlib only. Python >= 3.8.

Usage:
    python3 savia-dual-proxy.py [--config PATH]

Config file: ~/.savia/dual/config.json (generated by savia-dual-setup.sh)
Log file:    ~/.savia/dual/events.jsonl
"""
from __future__ import annotations
import argparse
import json
import logging
import os
import socket
import sys
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

import os

DEFAULT_ANTHROPIC_UPSTREAM = os.environ.get(
    "SAVIA_API_UPSTREAM", "https://api.anthropic.com"
)

DEFAULT_CONFIG: dict[str, Any] = {
    "listen_host": "127.0.0.1",
    "listen_port": 8787,
    "anthropic_upstream": DEFAULT_ANTHROPIC_UPSTREAM,
    "ollama_upstream": "http://127.0.0.1:11434",
    "fallback_triggers": {
        "network_error": True,
        "http_5xx": True,
        "http_429": True,
        "timeout_seconds": 30,
    },
    "circuit_breaker": {
        "consecutive_failures": 3,
        "cooldown_seconds": 60,
    },
    "local_model": "gemma4:e4b",
    "log_path": "~/.savia/dual/events.jsonl",
}


class CircuitBreaker:
    """Minimal circuit breaker. After N consecutive failures to primary,
    route directly to fallback for cooldown_seconds before retrying primary."""

    def __init__(self, threshold: int, cooldown: int) -> None:
        self.threshold = threshold
        self.cooldown = cooldown
        self.failures = 0
        self.opened_at: float | None = None
        self._lock = threading.Lock()

    def should_skip_primary(self) -> bool:
        with self._lock:
            if self.opened_at is None:
                return False
            if time.time() - self.opened_at >= self.cooldown:
                self.opened_at = None
                self.failures = 0
                return False
            return True

    def record_success(self) -> None:
        with self._lock:
            self.failures = 0
            self.opened_at = None

    def record_failure(self) -> None:
        with self._lock:
            self.failures += 1
            if self.failures >= self.threshold and self.opened_at is None:
                self.opened_at = time.time()


class DualProxy:
    def __init__(self, config: dict[str, Any]) -> None:
        self.config = config
        self.breaker = CircuitBreaker(
            config["circuit_breaker"]["consecutive_failures"],
            config["circuit_breaker"]["cooldown_seconds"],
        )
        log_path = Path(os.path.expanduser(config["log_path"]))
        log_path.parent.mkdir(parents=True, exist_ok=True)
        self.log_path = log_path
        self._log_lock = threading.Lock()

    def log_event(self, event: dict[str, Any]) -> None:
        event["ts"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        line = json.dumps(event, ensure_ascii=False)
        with self._log_lock:
            try:
                with self.log_path.open("a", encoding="utf-8") as fh:
                    fh.write(line + "\n")
            except OSError:
                pass

    def _should_fallback(self, status: int, err: Exception | None) -> str | None:
        triggers = self.config["fallback_triggers"]
        if err is not None:
            if triggers["network_error"]:
                return f"network_error:{type(err).__name__}"
            return None
        if status == 429 and triggers["http_429"]:
            return "http_429"
        if 500 <= status < 600 and triggers["http_5xx"]:
            return f"http_{status}"
        return None

    def _rewrite_for_ollama(self, body_bytes: bytes) -> bytes:
        try:
            body = json.loads(body_bytes.decode("utf-8"))
        except (ValueError, UnicodeDecodeError):
            return body_bytes
        model = body.get("model", "")
        if model and not model.startswith(("gemma", "llama", "qwen", "mistral", "phi")):
            body["model"] = self.config["local_model"]
        # Ollama ignores unknown fields but strip cache markers to be safe
        body.pop("metadata", None)
        return json.dumps(body).encode("utf-8")

    def _strip_hop_headers(self, headers: dict[str, str]) -> dict[str, str]:
        skip = {
            "host", "content-length", "connection", "keep-alive",
            "proxy-authenticate", "proxy-authorization", "te", "trailer",
            "transfer-encoding", "upgrade",
        }
        return {k: v for k, v in headers.items() if k.lower() not in skip}

    def forward(
        self,
        target: str,
        upstream_base: str,
        method: str,
        path: str,
        headers: dict[str, str],
        body: bytes,
        timeout: float,
    ) -> tuple[int, dict[str, str], bytes, Exception | None]:
        url = upstream_base.rstrip("/") + path
        fwd_headers = self._strip_hop_headers(headers)
        if target == "ollama":
            # Ollama doesn't need x-api-key; strip it for hygiene.
            fwd_headers.pop("x-api-key", None)
            fwd_headers.pop("X-Api-Key", None)
        req = urllib.request.Request(url, data=body if body else None, method=method)
        for k, v in fwd_headers.items():
            req.add_header(k, v)
        try:
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                raw = resp.read()
                resp_headers = {k: v for k, v in resp.getheaders()}
                return resp.status, resp_headers, raw, None
        except urllib.error.HTTPError as e:
            return e.code, dict(e.headers or {}), e.read() or b"", None
        except (urllib.error.URLError, socket.timeout, TimeoutError, ConnectionError) as e:
            return 0, {}, b"", e

    def handle_messages(
        self, method: str, path: str, headers: dict[str, str], body: bytes
    ) -> tuple[int, dict[str, str], bytes]:
        start = time.time()
        skip_primary = self.breaker.should_skip_primary()
        primary_status = 0
        primary_err: Exception | None = None
        fallback_reason: str | None = None

        if not skip_primary:
            primary_status, primary_headers, primary_body, primary_err = self.forward(
                target="anthropic",
                upstream_base=self.config["anthropic_upstream"],
                method=method,
                path=path,
                headers=headers,
                body=body,
                timeout=self.config["fallback_triggers"]["timeout_seconds"],
            )
            fallback_reason = self._should_fallback(primary_status, primary_err)
            if fallback_reason is None and primary_err is None and 200 <= primary_status < 400:
                self.breaker.record_success()
                self.log_event({
                    "route": "anthropic",
                    "status": primary_status,
                    "latency_ms": int((time.time() - start) * 1000),
                })
                return primary_status, primary_headers, primary_body
            self.breaker.record_failure()
        else:
            fallback_reason = "circuit_open"

        ollama_body = self._rewrite_for_ollama(body)
        ollama_status, ollama_headers, ollama_resp, ollama_err = self.forward(
            target="ollama",
            upstream_base=self.config["ollama_upstream"],
            method=method,
            path=path,
            headers=headers,
            body=ollama_body,
            timeout=120,
        )
        latency_ms = int((time.time() - start) * 1000)
        if ollama_err is not None:
            self.log_event({
                "route": "none",
                "status": 503,
                "fallback_reason": fallback_reason,
                "ollama_error": type(ollama_err).__name__,
                "latency_ms": latency_ms,
            })
            err_body = json.dumps({
                "type": "error",
                "error": {
                    "type": "upstream_unavailable",
                    "message": "Both Anthropic and Ollama are unavailable",
                    "fallback_reason": fallback_reason,
                    "ollama_error": str(ollama_err),
                },
            }).encode("utf-8")
            return 503, {"Content-Type": "application/json"}, err_body

        self.log_event({
            "route": "ollama",
            "status": ollama_status,
            "fallback_reason": fallback_reason,
            "local_model": self.config["local_model"],
            "latency_ms": latency_ms,
        })
        return ollama_status, ollama_headers, ollama_resp


class ProxyHandler(BaseHTTPRequestHandler):
    proxy: DualProxy  # injected

    def log_message(self, format: str, *args: Any) -> None:  # quiet stdout
        pass

    def _dispatch(self, method: str) -> None:
        length = int(self.headers.get("Content-Length", "0") or "0")
        body = self.rfile.read(length) if length > 0 else b""
        headers = {k: v for k, v in self.headers.items()}
        path = self.path
        if path == "/health":
            self._write(200, {"Content-Type": "application/json"},
                        json.dumps({"status": "ok"}).encode("utf-8"))
            return
        if not path.startswith("/v1/"):
            self._write(404, {"Content-Type": "application/json"},
                        b'{"error":"not_found"}')
            return
        status, resp_headers, resp_body = self.proxy.handle_messages(method, path, headers, body)
        self._write(status, resp_headers, resp_body)

    def _write(self, status: int, headers: dict[str, str], body: bytes) -> None:
        self.send_response(status)
        filtered = {k: v for k, v in headers.items()
                    if k.lower() not in ("transfer-encoding", "content-length", "connection")}
        for k, v in filtered.items():
            self.send_header(k, v)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self) -> None: self._dispatch("GET")
    def do_POST(self) -> None: self._dispatch("POST")


def load_config(path: Path) -> dict[str, Any]:
    if not path.exists():
        return DEFAULT_CONFIG
    with path.open("r", encoding="utf-8") as fh:
        user = json.load(fh)
    merged = json.loads(json.dumps(DEFAULT_CONFIG))
    merged.update({k: v for k, v in user.items() if k != "fallback_triggers" and k != "circuit_breaker"})
    if "fallback_triggers" in user:
        merged["fallback_triggers"].update(user["fallback_triggers"])
    if "circuit_breaker" in user:
        merged["circuit_breaker"].update(user["circuit_breaker"])
    return merged


def main() -> int:
    parser = argparse.ArgumentParser(description="Savia Dual failover proxy")
    parser.add_argument("--config", default="~/.savia/dual/config.json")
    parser.add_argument("--host", default=None)
    parser.add_argument("--port", type=int, default=None)
    args = parser.parse_args()
    config_path = Path(os.path.expanduser(args.config))
    config = load_config(config_path)
    if args.host:
        config["listen_host"] = args.host
    if args.port:
        config["listen_port"] = args.port
    proxy = DualProxy(config)
    ProxyHandler.proxy = proxy
    addr = (config["listen_host"], config["listen_port"])
    server = ThreadingHTTPServer(addr, ProxyHandler)
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(message)s")
    logging.info("savia-dual listening on http://%s:%d", *addr)
    logging.info("primary=%s fallback=%s model=%s",
                 config["anthropic_upstream"], config["ollama_upstream"], config["local_model"])
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        logging.info("shutdown")
    return 0


if __name__ == "__main__":
    sys.exit(main())
