#!/usr/bin/env bash
set -uo pipefail
# Force C locale for deterministic sort + awk text handling across machines
export LC_ALL=C
# skills-md-generate.sh — generate SKILLS.md cross-frontend skills catalog
#
# Mirror of scripts/agents-md-generate.sh for skills. Generates a flat
# catalog of all .opencode/skills/*/SKILL.md so that any frontend (OpenCode,
# Codex, Cursor, ...) can load it as a single instruction file. Supports
# the same modes (default print, --apply, --check) as the agents version.
#
# Reference: SE-078 cross-frontend mirror pattern
# Reference: SPEC-127 OpenCode bootstrap

ROOT="${PROJECT_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
SKILLS_DIR="${SKILLS_DIR:-${ROOT}/.opencode/skills}"
TARGET="${SKILLS_MD:-${ROOT}/SKILLS.md}"
MODE="generate"

usage() {
  cat <<USG
Usage: skills-md-generate.sh [--apply | --check]

Modes:
  (default)  Print SKILLS.md content to stdout (dry run)
  --apply    Write SKILLS.md atomically
  --check    Exit 1 if generated content differs from on-disk SKILLS.md
USG
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --apply)  MODE="apply"; shift ;;
    --check)  MODE="check"; shift ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; usage >&2; exit 2 ;;
  esac
done

[[ -d "$SKILLS_DIR" ]] || { echo "ERROR: skills dir not found: $SKILLS_DIR" >&2; exit 3; }

extract_field() {
  local file="$1" field="$2"
  awk -v field="^${field}:" '
    /^---$/ { c++; if (c>=2) exit; next }
    c==1 {
      if ($0 ~ field) {
        sub(field, ""); sub(/^[[:space:]]+/, "")
        if ($0 ~ /^>/) { collecting = 1; buf = ""; next }
        gsub(/^"|"$/, ""); print; exit
      }
      if (collecting) {
        if ($0 ~ /^[[:alpha:]_][^[:space:]]*:/) {
          gsub(/^[[:space:]]+|[[:space:]]+$/, "", buf); print buf; exit
        }
        gsub(/^[[:space:]]+|[[:space:]]+$/, "")
        if ($0 != "") buf = buf " " $0
      }
    }
    END {
      if (collecting) { gsub(/^[[:space:]]+|[[:space:]]+$/, "", buf); print buf }
    }
  ' "$file"
}

sanitise() {
  local s="$1"
  s=$(printf '%s' "$s" | tr -s '[:space:]' ' ' | sed -E 's/^ +| +$//g')
  s="${s//|/\\|}"
  if [[ ${#s} -gt 100 ]]; then s="${s:0:97}..."; fi
  printf '%s' "$s"
}

build() {
  cat <<'HEADER'
# SKILLS.md

> Auto-generated from `.opencode/skills/*/SKILL.md`. **Do not edit by hand.**
> Cross-frontend skills catalog. Generated by `scripts/skills-md-generate.sh`.

## How to use

This is the cross-frontend mirror of Savia's skills registry. Claude Code
reads `.opencode/skills/*/SKILL.md` directly; OpenCode v1.14, Codex, Cursor
and other frontends can load this `SKILLS.md` as freeform context. Source
of truth is each individual `SKILL.md`; this index is regenerated when a
skill is added or modified.

To use a skill: read `<path>` and follow its instructions.

## Skills

| Name | Path | Description |
|---|---|---|
HEADER
  while IFS= read -r f; do
    [[ -f "$f" ]] || continue
    local name desc rel
    name=$(extract_field "$f" "name")
    [[ -z "$name" ]] && {
      # Fallback: derive name from parent directory
      name=$(basename "$(dirname "$f")")
    }
    desc=$(extract_field "$f" "description")
    desc=$(sanitise "$desc")
    [[ -z "$desc" ]] && desc="—"
    rel="${f#${ROOT}/}"
    printf '| %s | `%s` | %s |\n' "$name" "$rel" "$desc"
  done < <(find -L "${SKILLS_DIR}" -mindepth 2 -maxdepth 2 -name "SKILL.md" -type f | LC_ALL=C sort)
}

GENERATED=$(build)

case "$MODE" in
  generate) printf '%s\n' "$GENERATED" ;;
  apply)
    tmp=$(mktemp)
    printf '%s\n' "$GENERATED" > "$tmp"
    mv "$tmp" "$TARGET"
    echo "wrote ${TARGET} ($(wc -l < "$TARGET") lines)"
    ;;
  check)
    if [[ ! -f "$TARGET" ]]; then
      echo "drift: $TARGET missing — run --apply" >&2
      exit 1
    fi
    if diff -u "$TARGET" <(printf '%s\n' "$GENERATED") >/dev/null; then
      echo "in sync"
    else
      echo "drift detected — run --apply" >&2
      exit 1
    fi
    ;;
esac
