#!/usr/bin/env bash
# slm-modelfile-gen.sh — Generate Ollama Modelfile for a trained SLM.
#
# Produce un Modelfile compatible con `ollama create` a partir de:
#   - Un GGUF path (modelo ya merged + cuantizado)
#   - Parámetros de persona/system prompt
#   - Parámetros de inferencia (temperature, num_ctx, stop tokens)
#
# NO ejecuta `ollama create` — solo emite el Modelfile text. El usuario
# lo aplica manualmente cuando tenga Ollama instalado + el GGUF listo.
#
# Usage:
#   slm-modelfile-gen.sh --name savia-context --gguf adapter.gguf --output Modelfile
#   slm-modelfile-gen.sh --name x --gguf x.gguf --output M --persona savia \
#     --temperature 0.4 --num-ctx 4096
#
# Exit codes:
#   0 — Modelfile emitted
#   2 — usage error
#
# Ref: SPEC-SE-027 §5 Integration Savia Dual, docs/rules/domain/slm-training-pipeline.md
# Safety: read-only del GGUF (solo referenciado por path), set -uo pipefail.

set -uo pipefail

NAME=""
GGUF=""
OUTPUT=""
PERSONA="default"
TEMPERATURE="0.4"
NUM_CTX="2048"
TOP_P="0.9"
SYSTEM_MESSAGE=""

# Persona allow-list (pre-built system prompts).
declare -A PERSONAS=(
  [default]="You are a helpful assistant. Be concise and accurate."
  [savia]="Eres Savia, una buhita (búho en femenino) asistente de pm-workspace. Habla siempre en femenino. Radically honest — sin filler, sin sugar-coating. Datos antes que sentimientos. Respuestas directas."
  [code-reviewer]="You are a code reviewer. Focus on correctness, security, and maintainability. Be direct. Point out issues without hedging."
  [pii-classifier]="You classify text as CONFIDENTIAL (contains PII or credentials), PUBLIC (safe to share), or AMBIGUOUS. Output only one word."
  [spec-assistant]="You help write and refine technical specifications. Use YAML frontmatter. Enforce acceptance criteria structure."
)

usage() {
  cat <<EOF
Usage:
  $0 --name NAME --gguf PATH --output FILE [options]

Required:
  --name NAME           Ollama model name (slug)
  --gguf PATH           Path to GGUF file (can be relative to Modelfile location)
  --output FILE         Modelfile destination

Optional:
  --persona NAME        Allowed: $(echo "${!PERSONAS[*]}" | tr ' ' ',')
                        default: default
  --system TEXT         Custom system message (overrides --persona)
  --temperature FLOAT   Inference temperature (default 0.4)
  --num-ctx N           Context window (default 2048)
  --top-p FLOAT         Top-p sampling (default 0.9)

NOTA: Este script NO ejecuta 'ollama create'. Tras generar el Modelfile:
     ollama create $NAME -f <Modelfile>

Ref: docs/rules/domain/slm-training-pipeline.md §5
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name) NAME="$2"; shift 2 ;;
    --gguf) GGUF="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    --persona) PERSONA="$2"; shift 2 ;;
    --system) SYSTEM_MESSAGE="$2"; shift 2 ;;
    --temperature) TEMPERATURE="$2"; shift 2 ;;
    --num-ctx) NUM_CTX="$2"; shift 2 ;;
    --top-p) TOP_P="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "ERROR: unknown arg '$1'" >&2; exit 2 ;;
  esac
done

[[ -z "$NAME" ]] && { echo "ERROR: --name required" >&2; exit 2; }
[[ -z "$GGUF" ]] && { echo "ERROR: --gguf required" >&2; exit 2; }
[[ -z "$OUTPUT" ]] && { echo "ERROR: --output required" >&2; exit 2; }

# Validate name slug.
if ! [[ "$NAME" =~ ^[a-z0-9][a-z0-9._:-]*$ ]]; then
  echo "ERROR: --name must be slug (lowercase, digits, dots, dashes, underscores, colons for tag)" >&2
  exit 2
fi

# Resolve system message: --system takes precedence over --persona allow-list.
if [[ -z "$SYSTEM_MESSAGE" ]]; then
  if [[ -z "${PERSONAS[$PERSONA]:-}" ]]; then
    echo "ERROR: unknown --persona '$PERSONA' (allowed: ${!PERSONAS[*]})" >&2
    exit 2
  fi
  SYSTEM_MESSAGE="${PERSONAS[$PERSONA]}"
fi

# Validate floats.
for var in TEMPERATURE TOP_P; do
  val="${!var}"
  if ! [[ "$val" =~ ^0?\.[0-9]+$|^1\.0*$|^[01]$ ]]; then
    echo "ERROR: $var must be between 0.0 and 1.0, got '$val'" >&2
    exit 2
  fi
done

# Validate int.
if ! [[ "$NUM_CTX" =~ ^[0-9]+$ ]] || [[ "$NUM_CTX" -le 0 ]]; then
  echo "ERROR: --num-ctx must be positive integer, got '$NUM_CTX'" >&2
  exit 2
fi

# Emit Modelfile.
cat > "$OUTPUT" <<MODELFILE
# Ollama Modelfile generated by scripts/slm-modelfile-gen.sh
# Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Ref: docs/rules/domain/slm-training-pipeline.md §5
#
# To deploy this model:
#   ollama create $NAME -f $(basename "$OUTPUT")
#
# To run interactively:
#   ollama run $NAME

FROM $GGUF

# System prompt (persona: $PERSONA)
SYSTEM """$SYSTEM_MESSAGE"""

# Inference parameters
PARAMETER temperature $TEMPERATURE
PARAMETER top_p $TOP_P
PARAMETER num_ctx $NUM_CTX
PARAMETER repeat_penalty 1.1
PARAMETER stop "<|im_end|>"
PARAMETER stop "<|eot_id|>"
PARAMETER stop "</s>"

# Template (ChatML-compatible — works for Llama-3, Qwen, most Unsloth finetunes)
TEMPLATE """{{ if .System }}<|im_start|>system
{{ .System }}<|im_end|>
{{ end }}{{ range .Messages }}<|im_start|>{{ .Role }}
{{ .Content }}<|im_end|>
{{ end }}<|im_start|>assistant
"""
MODELFILE

echo "slm-modelfile-gen: wrote $OUTPUT"
echo "  name:        $NAME"
echo "  gguf:        $GGUF"
echo "  persona:     $PERSONA"
echo "  temperature: $TEMPERATURE"
echo "  num_ctx:     $NUM_CTX"
echo ""
echo "Next: ollama create $NAME -f $(basename "$OUTPUT")"

exit 0
