#!/usr/bin/env bash
# slm-train-config.sh — Phase 3 scaffolding: emit Unsloth/TRL YAML config.
#
# Genera un archivo YAML de configuración de entrenamiento Unsloth + TRL
# con parámetros validados. NO ejecuta entrenamiento — solo emite config
# para ser usada por `python train.py --config <yaml>` cuando haya GPU.
#
# Usage:
#   slm-train-config.sh --model llama-3.2-1b --dataset data.jsonl --output config.yaml
#   slm-train-config.sh --model qwen2.5-0.5b --dataset d.jsonl --output c.yaml \
#     --lora-r 16 --lora-alpha 16 --epochs 3 --lr 2e-4 --batch-size 2
#
# Exit codes:
#   0 — config emitted
#   2 — usage error
#
# Ref: SPEC-SE-027, SPEC-080, docs/rules/domain/slm-training-pipeline.md §Fase 3
# Safety: read-only filesystem (solo escribe --output), set -uo pipefail.

set -uo pipefail

MODEL=""
DATASET=""
OUTPUT=""
LORA_R=16
LORA_ALPHA=16
LORA_DROPOUT=0.1
EPOCHS=3
LEARNING_RATE="2e-4"
BATCH_SIZE=2
MAX_SEQ_LEN=2048
LOAD_IN_4BIT="true"
OUTPUT_DIR="./checkpoints"

# Allowlist of base models with validated sizes.
declare -A VALID_MODELS=(
  [llama-3.2-1b]="unsloth/Llama-3.2-1B-Instruct-bnb-4bit"
  [llama-3.2-3b]="unsloth/Llama-3.2-3B-Instruct-bnb-4bit"
  [qwen2.5-0.5b]="unsloth/Qwen2.5-0.5B-Instruct-bnb-4bit"
  [qwen2.5-3b]="unsloth/Qwen2.5-3B-Instruct-bnb-4bit"
  [phi-3.5-mini]="unsloth/Phi-3.5-mini-instruct-bnb-4bit"
)

usage() {
  cat <<EOF
Usage:
  $0 --model MODEL --dataset FILE --output CONFIG.yaml [options]

Required:
  --model MODEL       one of: llama-3.2-1b, llama-3.2-3b, qwen2.5-0.5b, qwen2.5-3b, phi-3.5-mini
  --dataset FILE      path to dataset JSONL (Alpaca/Unsloth format)
  --output FILE       config.yaml destination

Optional LoRA params:
  --lora-r N          LoRA rank (default 16)
  --lora-alpha N      LoRA alpha (default 16)
  --lora-dropout F    LoRA dropout (default 0.1)

Optional training params:
  --epochs N          epochs (default 3)
  --lr FLOAT          learning rate (default 2e-4)
  --batch-size N      per-device batch (default 2)
  --max-seq-len N     max sequence length (default 2048)

Ref: docs/rules/domain/slm-training-pipeline.md §Fase 3
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --model) MODEL="$2"; shift 2 ;;
    --dataset) DATASET="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    --lora-r) LORA_R="$2"; shift 2 ;;
    --lora-alpha) LORA_ALPHA="$2"; shift 2 ;;
    --lora-dropout) LORA_DROPOUT="$2"; shift 2 ;;
    --epochs) EPOCHS="$2"; shift 2 ;;
    --lr) LEARNING_RATE="$2"; shift 2 ;;
    --batch-size) BATCH_SIZE="$2"; shift 2 ;;
    --max-seq-len) MAX_SEQ_LEN="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "ERROR: unknown arg '$1'" >&2; exit 2 ;;
  esac
done

[[ -z "$MODEL" ]] && { echo "ERROR: --model required" >&2; exit 2; }
[[ -z "$DATASET" ]] && { echo "ERROR: --dataset required" >&2; exit 2; }
[[ -z "$OUTPUT" ]] && { echo "ERROR: --output required" >&2; exit 2; }

if [[ -z "${VALID_MODELS[$MODEL]:-}" ]]; then
  echo "ERROR: invalid --model '$MODEL'" >&2
  echo "Allowed: ${!VALID_MODELS[*]}" >&2
  exit 2
fi

MODEL_PATH="${VALID_MODELS[$MODEL]}"

# Validate numeric params.
for var in LORA_R LORA_ALPHA EPOCHS BATCH_SIZE MAX_SEQ_LEN; do
  val="${!var}"
  if ! [[ "$val" =~ ^[0-9]+$ ]]; then
    echo "ERROR: $var must be integer, got '$val'" >&2
    exit 2
  fi
  if [[ "$val" -le 0 ]]; then
    echo "ERROR: $var must be positive, got '$val'" >&2
    exit 2
  fi
done

# Validate float params (basic regex).
for var in LORA_DROPOUT LEARNING_RATE; do
  val="${!var}"
  if ! [[ "$val" =~ ^[0-9]+(\.[0-9]+)?(e-?[0-9]+)?$ ]]; then
    echo "ERROR: $var must be valid float/scientific notation, got '$val'" >&2
    exit 2
  fi
done

# Emit YAML.
cat > "$OUTPUT" <<YAML
# Unsloth + TRL training config (SE-027 / SPEC-080)
# Generated by scripts/slm-train-config.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Ref: docs/rules/domain/slm-training-pipeline.md

model:
  name: "${MODEL}"
  path: "${MODEL_PATH}"
  max_seq_length: ${MAX_SEQ_LEN}
  load_in_4bit: ${LOAD_IN_4BIT}
  dtype: "auto"

dataset:
  path: "${DATASET}"
  format: "alpaca"
  shuffle: true

lora:
  r: ${LORA_R}
  alpha: ${LORA_ALPHA}
  dropout: ${LORA_DROPOUT}
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj
  bias: "none"
  use_gradient_checkpointing: "unsloth"

training:
  output_dir: "${OUTPUT_DIR}"
  num_train_epochs: ${EPOCHS}
  per_device_train_batch_size: ${BATCH_SIZE}
  gradient_accumulation_steps: 4
  learning_rate: ${LEARNING_RATE}
  warmup_ratio: 0.03
  lr_scheduler_type: "linear"
  optim: "adamw_8bit"
  weight_decay: 0.01
  fp16: false
  bf16: true
  logging_steps: 10
  save_strategy: "epoch"
  save_total_limit: 2
  seed: 42

reporting:
  report_to: "none"  # offline — no WandB/Tensorboard external
  log_file: "training.log"

sovereignty:
  zero_egress: true
  hardware_required: "CUDA GPU ≥8GB VRAM for ${MODEL}"
  data_sources: ["local"]
YAML

echo "slm-train-config: wrote ${OUTPUT}"
echo "  model=${MODEL} (${MODEL_PATH})"
echo "  dataset=${DATASET}"
echo "  lora r=${LORA_R} alpha=${LORA_ALPHA} dropout=${LORA_DROPOUT}"
echo "  epochs=${EPOCHS} lr=${LEARNING_RATE} batch=${BATCH_SIZE}"
echo "  Hint: run 'python scripts/slm-train.py --config ${OUTPUT}' when GPU available."

exit 0
