#!/usr/bin/env bash
# slm-export-gguf.sh — Generate llama.cpp conversion recipe for adapter→GGUF.
#
# Emite:
#   - `export.sh` script con comandos llama.cpp listo para ejecutar
#   - `export-manifest.json` con metadata (base, adapter, cuantización, hashes)
#
# NO ejecuta la conversión — emite los comandos. La conversión real requiere
# llama.cpp compilado + base model + adapter weights.
#
# Usage:
#   slm-export-gguf.sh --base llama-3.2-1b --adapter ./adapters/sft-v1 \
#     --output-dir ./gguf --quantization q4_k_m
#
# Exit codes:
#   0 — recipe emitted
#   2 — usage error
#
# Ref: SPEC-SE-027 §Export, docs/rules/domain/slm-training-pipeline.md §Fase 5
# Safety: read-only, set -uo pipefail.

set -uo pipefail

BASE=""
ADAPTER=""
OUTPUT_DIR=""
QUANTIZATION="q4_k_m"
NAME=""

VALID_QUANT="q2_k q3_k q4_0 q4_k_s q4_k_m q5_0 q5_k_s q5_k_m q6_k q8_0 f16 f32"

usage() {
  cat <<EOF
Usage:
  $0 --base MODEL --adapter PATH --output-dir DIR [options]

Required:
  --base MODEL          Base model name (ej. llama-3.2-1b)
  --adapter PATH        Path a LoRA adapter directory
  --output-dir DIR      Destination for export.sh + manifest.json

Optional:
  --quantization Q      $VALID_QUANT (default q4_k_m)
  --name NAME           Output name (default: derived from base)

Emite recipe (export.sh + manifest.json). NO ejecuta llama.cpp — el usuario
corre 'bash <output-dir>/export.sh' cuando tenga llama.cpp compilado.

Ref: SPEC-SE-027 §Export
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base) BASE="$2"; shift 2 ;;
    --adapter) ADAPTER="$2"; shift 2 ;;
    --output-dir) OUTPUT_DIR="$2"; shift 2 ;;
    --quantization) QUANTIZATION="$2"; shift 2 ;;
    --name) NAME="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "ERROR: unknown arg '$1'" >&2; exit 2 ;;
  esac
done

[[ -z "$BASE" ]] && { echo "ERROR: --base required" >&2; exit 2; }
[[ -z "$ADAPTER" ]] && { echo "ERROR: --adapter required" >&2; exit 2; }
[[ -z "$OUTPUT_DIR" ]] && { echo "ERROR: --output-dir required" >&2; exit 2; }

# Validate quantization.
if ! echo " $VALID_QUANT " | grep -q " $QUANTIZATION "; then
  echo "ERROR: invalid --quantization '$QUANTIZATION' (allowed: $VALID_QUANT)" >&2
  exit 2
fi

# Derive name from base if not given.
: "${NAME:=${BASE}-finetuned}"

# Validate name.
if ! [[ "$NAME" =~ ^[a-zA-Z0-9][a-zA-Z0-9._-]*$ ]]; then
  echo "ERROR: --name must be slug (alphanumeric + . _ -), got '$NAME'" >&2
  exit 2
fi

mkdir -p "$OUTPUT_DIR"

# Emit export.sh.
EXPORT_SH="$OUTPUT_DIR/export.sh"
MANIFEST="$OUTPUT_DIR/export-manifest.json"
GGUF_OUT="${NAME}.${QUANTIZATION}.gguf"

cat > "$EXPORT_SH" <<BASH
#!/usr/bin/env bash
# export.sh — Convert LoRA adapter + base model → GGUF
# Generated by scripts/slm-export-gguf.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Ref: docs/rules/domain/slm-training-pipeline.md §Fase 5
#
# Prerequisites:
#   - llama.cpp compiled (https://github.com/ggerganov/llama.cpp)
#   - Base model downloaded from HuggingFace
#   - LoRA adapter weights trained and saved

set -euo pipefail

LLAMA_CPP="\${LLAMA_CPP:-\$HOME/src/llama.cpp}"
BASE_HF="\${BASE_HF:-./base-model}"         # base model in HF safetensors format
ADAPTER="$ADAPTER"
OUTPUT_DIR="$(realpath "$OUTPUT_DIR")"
GGUF_OUT="\$OUTPUT_DIR/$GGUF_OUT"
QUANT="$QUANTIZATION"

# Step 1: Merge adapter into base.
echo "[1/3] Merging LoRA adapter with base model..."
python "\$LLAMA_CPP/convert_lora_to_gguf.py" \\
  --base "\$BASE_HF" \\
  --lora-path "\$ADAPTER" \\
  --outfile "\$OUTPUT_DIR/${NAME}.f16.gguf" \\
  --outtype f16

# Step 2: Quantize.
echo "[2/3] Quantizing to \$QUANT..."
"\$LLAMA_CPP/build/bin/llama-quantize" \\
  "\$OUTPUT_DIR/${NAME}.f16.gguf" \\
  "\$GGUF_OUT" \\
  "\$QUANT"

# Step 3: Compute checksum + size.
echo "[3/3] Computing checksums..."
SHA=\$(sha256sum "\$GGUF_OUT" | awk '{print \$1}')
SIZE=\$(stat -c%s "\$GGUF_OUT")
echo "GGUF: \$GGUF_OUT"
echo "SHA-256: \$SHA"
echo "Size:    \$SIZE bytes (\$(numfmt --to=iec \$SIZE))"

# Optional: remove intermediate f16 to save disk.
# rm -f "\$OUTPUT_DIR/${NAME}.f16.gguf"

echo "✅ Done. Deploy with:"
echo "   bash scripts/slm-modelfile-gen.sh --name $NAME --gguf \$GGUF_OUT --output Modelfile"
echo "   ollama create $NAME -f Modelfile"
BASH

chmod +x "$EXPORT_SH"

# Emit manifest.
cat > "$MANIFEST" <<JSON
{
  "generated_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "base": "$BASE",
  "adapter": "$ADAPTER",
  "name": "$NAME",
  "quantization": "$QUANTIZATION",
  "expected_output": "$GGUF_OUT",
  "export_script": "$(basename "$EXPORT_SH")",
  "steps": 3,
  "prerequisites": [
    "llama.cpp compiled",
    "base model in HF format",
    "LoRA adapter weights"
  ],
  "note": "Recipe only — does not execute conversion. Run export.sh when prerequisites ready."
}
JSON

echo "slm-export-gguf: recipe emitted"
echo "  script:    $EXPORT_SH"
echo "  manifest:  $MANIFEST"
echo "  name:      $NAME"
echo "  quant:     $QUANTIZATION"
echo "  expected:  $GGUF_OUT"
echo ""
echo "Next: ensure llama.cpp + base model + adapter ready, then run: bash $EXPORT_SH"

exit 0
