#!/usr/bin/env bash
# slm-synth-recipe.sh — SE-028 Slice 1 scaffolding: emit oumi synth recipe YAML.
#
# Genera un YAML compatible con `oumi synth` para generación sintética de
# datos de entrenamiento. NO ejecuta oumi — emite el recipe; la ejecución
# real requiere `pip install oumi` + LLM judge/frontier.
#
# Supported strategies (SE-028 §2):
#   - qa-pairs          Genera Q&A pairs desde corpus de texto
#   - paraphrase        Paraphrasea respuestas originales (augmentation)
#   - code-explain      De código → explicación natural (para code models)
#   - distillation      Frontier model → student (requires API frontier)
#   - self-instruct     Seed instructions → expanded set
#
# Usage:
#   slm-synth-recipe.sh --strategy qa-pairs --input corpus.md --output recipe.yaml
#   slm-synth-recipe.sh --strategy paraphrase --input base.jsonl --output r.yaml \
#     --judge-model local --target-samples 1000
#
# Exit codes:
#   0 — recipe emitted
#   2 — usage error
#
# Ref: SE-028, docs/rules/domain/slm-training-pipeline.md §Fase 2
# Safety: read-only filesystem, set -uo pipefail.

set -uo pipefail

STRATEGY=""
INPUT=""
OUTPUT=""
TARGET_SAMPLES=500
JUDGE_MODEL="local"
TEMPERATURE=0.7

VALID_STRATEGIES="qa-pairs paraphrase code-explain distillation self-instruct"

usage() {
  cat <<EOF
Usage:
  $0 --strategy STRAT --input FILE --output RECIPE.yaml [options]

Required:
  --strategy STRAT    one of: $VALID_STRATEGIES
  --input FILE        corpus o base dataset
  --output FILE       recipe YAML destino

Optional:
  --target-samples N  muestras objetivo (default 500)
  --judge-model M     local | claude-haiku-4-5 | claude-sonnet-4-6 (default local)
  --temperature F     0.0-1.0 (default 0.7)

NOTA: este script NO ejecuta oumi — solo emite el recipe. Ejecución real:
     oumi synth --config <RECIPE.yaml>
  con 'pip install oumi' + credenciales LLM si aplica.

Ref: docs/rules/domain/slm-training-pipeline.md §Fase 2 (SE-028)
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --strategy) STRATEGY="$2"; shift 2 ;;
    --input) INPUT="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    --target-samples) TARGET_SAMPLES="$2"; shift 2 ;;
    --judge-model) JUDGE_MODEL="$2"; shift 2 ;;
    --temperature) TEMPERATURE="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "ERROR: unknown arg '$1'" >&2; exit 2 ;;
  esac
done

[[ -z "$STRATEGY" ]] && { echo "ERROR: --strategy required" >&2; exit 2; }
[[ -z "$INPUT" ]] && { echo "ERROR: --input required" >&2; exit 2; }
[[ -z "$OUTPUT" ]] && { echo "ERROR: --output required" >&2; exit 2; }
[[ ! -f "$INPUT" ]] && { echo "ERROR: input file not found: $INPUT" >&2; exit 2; }

# Validate strategy allow-list.
if ! echo " $VALID_STRATEGIES " | grep -q " $STRATEGY "; then
  echo "ERROR: invalid --strategy '$STRATEGY' (allowed: $VALID_STRATEGIES)" >&2
  exit 2
fi

# Validate numeric.
if ! [[ "$TARGET_SAMPLES" =~ ^[0-9]+$ ]] || [[ "$TARGET_SAMPLES" -le 0 ]]; then
  echo "ERROR: --target-samples must be positive integer" >&2
  exit 2
fi

if ! [[ "$TEMPERATURE" =~ ^0?\.[0-9]+$|^1\.0*$|^0\.?$ ]]; then
  echo "ERROR: --temperature must be between 0.0 and 1.0" >&2
  exit 2
fi

# Validate judge model allow-list.
case "$JUDGE_MODEL" in
  local|claude-haiku-4-5|claude-sonnet-4-6|ollama-qwen-2.5) ;;
  *) echo "ERROR: invalid --judge-model '$JUDGE_MODEL'" >&2; exit 2 ;;
esac

# Emit YAML.
cat > "$OUTPUT" <<YAML
# oumi synth recipe (SE-028 Fase 2)
# Generated by scripts/slm-synth-recipe.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Ref: docs/rules/domain/slm-training-pipeline.md §Fase 2
#
# NOTA: este recipe NO se ejecuta automáticamente. Para correr:
#   oumi synth --config ${OUTPUT}
# Requiere: pip install oumi + credenciales si judge-model != local.

synth:
  strategy: "${STRATEGY}"
  input:
    path: "${INPUT}"
YAML

# Strategy-specific input format hint.
case "$STRATEGY" in
  qa-pairs)
    cat >> "$OUTPUT" <<YAML
    format: "corpus"      # plain text chunks
    chunk_size_tokens: 512
  generation:
    prompt_template: "Generate a Q&A pair from this text. Question must be answerable from the text alone."
    max_questions_per_chunk: 3
YAML
    ;;
  paraphrase)
    cat >> "$OUTPUT" <<YAML
    format: "jsonl"       # expects {instruction, output} pairs
  generation:
    prompt_template: "Paraphrase the response below while preserving exact facts."
    paraphrase_variants: 2
YAML
    ;;
  code-explain)
    cat >> "$OUTPUT" <<YAML
    format: "code-corpus" # source files
    extensions: [".py", ".sh", ".ts", ".cs"]
  generation:
    prompt_template: "Explain this code block in plain language. Preserve function names."
    chunk_granularity: "function"
YAML
    ;;
  distillation)
    cat >> "$OUTPUT" <<YAML
    format: "jsonl"
  generation:
    teacher_model: "${JUDGE_MODEL}"
    prompt_template: "Respond as a domain expert. Be concise and factual."
    include_chain_of_thought: false
YAML
    ;;
  self-instruct)
    cat >> "$OUTPUT" <<YAML
    format: "seed-instructions"
  generation:
    seed_tasks_count: 50
    prompt_template: "Generate a diverse new instruction similar in topic but distinct."
    expansion_factor: 10
YAML
    ;;
esac

cat >> "$OUTPUT" <<YAML

judge:
  model: "${JUDGE_MODEL}"
  rubric:
    - correctness
    - diversity
    - no_pii
    - matches_style
  pass_threshold: 0.8

output:
  target_samples: ${TARGET_SAMPLES}
  dedup: true
  dedup_similarity_threshold: 0.85
  format: "alpaca"          # Unsloth-compatible
  path: "${INPUT%.*}.synthesized.jsonl"

sampling:
  temperature: ${TEMPERATURE}
  top_p: 0.95
  max_new_tokens: 512

safety:
  pii_filter: true          # regex scan + redact emails/phones/DNI
  content_filter: true      # toxicity, hate speech
  quality_gate: 0.7         # reject samples below rubric score

sovereignty:
  zero_egress: $(if [[ "$JUDGE_MODEL" == "local" || "$JUDGE_MODEL" == ollama* ]]; then echo "true"; else echo "false"; fi)
  judge_location: "$(if [[ "$JUDGE_MODEL" == "local" || "$JUDGE_MODEL" == ollama* ]]; then echo local; else echo cloud-api; fi)"
  note: "If judge_location=cloud-api, sample batches may include data fragments. Review privacy impact."
YAML

echo "slm-synth-recipe: wrote ${OUTPUT}"
echo "  strategy:       ${STRATEGY}"
echo "  input:          ${INPUT}"
echo "  target_samples: ${TARGET_SAMPLES}"
echo "  judge_model:    ${JUDGE_MODEL}"
echo "  temperature:    ${TEMPERATURE}"
echo ""
echo "Next: run 'oumi synth --config ${OUTPUT}' when oumi installed."

exit 0
