# communication — Savia Capability Map (L1)
> 85 resources

- **chat-notify** (cmd): Enviar notificación formateada a Google Chat
- **chat-setup** (cmd): Guía de configuración de webhook de Google Chat
- **excel-digest** (agent): >
- **inbox-check** (cmd): >
- **inbox-start** (cmd): >
- **masked-digest** (script): masked-digest.sh — Masked digestion pipeline
- **meeting-agenda** (cmd): Generación inteligente de agendas basada en estado del sprint y temas pendientes
- **meeting-confidentiality-judge** (agent): >
- **meeting-digest** (cmd): >
- **meeting-digest** (agent): >
- **meeting-risk-analyst** (agent): >
- **meeting-summarize** (cmd): Transcribe y extrae action items de reuniones — Sprint Review, Retro, Planning, Daily
- **nctalk-search** (cmd): >
- **notify** (script): notify.sh — Cross-platform desktop notifications for Savia
- **notify-nctalk** (cmd): >
- **notify-slack** (cmd): >
- **notify-whatsapp** (cmd): >
- **obs-dashboard** (cmd): Dashboard de observabilidad digesto por rol — CEO, CTO, PM, Dev, QA, SRE
- **pdf-digest** (agent): >
- **pptx-digest** (agent): >
- **savia-announce** (cmd): >
- **savia-backup** (script): Savia Backup & Restore Script
- **savia-board** (cmd): >
- **savia-branch** (script): savia-branch.sh — Git branch abstraction layer for Company Savia v3
- **savia-broadcast** (cmd): >
- **savia-compat** (script): savia-compat.sh — Portable helpers for cross-platform compatibility
- **savia-crypto** (script): savia-crypto.sh — RSA + AES hybrid encryption using openssl only
- **savia-crypto-ops** (script): savia-crypto-ops.sh — Encrypt and decrypt operations
- **savia-directory** (cmd): >
- **savia-dual** (cmd): Gestiona Savia Dual — inference sovereignty con failover entre Anthropic y gemma4 local
- **savia-dual** (skill): Inference sovereignty — transparent failover from Anthropic to local gemma4 when the cloud is slow, failing, rate-limited, or unreachable
- **savia-enterprise** (script): savia-enterprise.sh — Enterprise module lifecycle manager
- **savia-env** (script): savia-env.sh — provider-agnostic environment loader (SPEC-127 Slice 1)
- **savia-flow** (script): savia-flow.sh — Git-based project management: PBIs, sprints, boards via branch isolation
- **savia-flow-board** (script): savia-flow-board.sh — ASCII Kanban board renderer via branch isolation
- **savia-flow-ops** (script): savia-flow-ops.sh — CRUD operations for PBIs and assignments via branch isolation
- **savia-flow-practice** (skill): Implementación práctica de Savia Flow — dual-track, specs ejecutables, métricas de flujo
- **savia-flow-sprint** (script): savia-flow-sprint.sh — Sprint lifecycle via branch isolation
- **savia-flow-tasks** (script): savia-flow-tasks.sh — Task management (delegates to savia-flow-ops.sh)
- **savia-flow-templates** (script): savia-flow-templates.sh — Project/team/member scaffolding via branch isolation
- **savia-flow-timesheet** (script): savia-flow-timesheet.sh — Time tracking via user branch
- **savia-forget** (cmd): >
- **savia-gallery** (cmd): Catálogo visual/interactivo de comandos, skills y agentes por rol y vertical
- **savia-hub** (cmd): Central hub for accessing Savia knowledge and tools
- **savia-hub-init** (script): savia-hub-init.sh — Initialize SaviaHub local repository
- **savia-hub-sync** (skill): Orquestación de sincronización del repositorio SaviaHub
- **savia-inbox** (cmd): >
- **savia-index** (script): ── savia-index.sh ──────────────────────────────────────────────────────────
- **savia-index-rebuild** (script): ── savia-index-rebuild.sh ──────────────────────────────────────────────────
- **savia-live** (cmd): Show what Savia is working on right now — live task queue and recent activity
- **savia-memory-bootstrap** (script): savia-memory-bootstrap.sh — crea store externo canónico ../.savia-memory/
- **savia-memory-migrate** (script): savia-memory-migrate.sh — migra memoria de silos internos/externos al store canónico
- **savia-messaging** (script): savia-messaging.sh — Message creation, delivery, and inbox management
- **savia-messaging-actions** (script): savia-messaging-actions.sh — Announce, broadcast, and directory operations
- **savia-messaging-inbox** (script): savia-messaging-inbox.sh — Inbox, read, and reply operations
- **savia-messaging-privacy** (script): savia-messaging-privacy.sh — Subject sensitivity check
- **savia-pbi** (cmd): >
- **savia-persona-tune** (cmd): Ajustar tono, estilo y personalidad de Savia para un proyecto específico
- **savia-preferences** (script): savia-preferences.sh — manage ~/.savia/preferences.yaml (SPEC-127 Slice 1)
- **savia-recall** (cmd): Recall and retrieve information from Savia memory
- **savia-reply** (cmd): >
- **savia-school** (skill): Adapta pm-workspace para entornos educativos con estudiantes menores de edad. Matriculacion por alias, evaluacion con rubricas, portfolio versionado y cumplimiento RGPD/LOPD estricto.
- **savia-school** (script): Savia School: Core educational vertical management library
- **savia-school-security** (script): Savia School Security Layer: Encryption, Access Control, GDPR
- **savia-send** (cmd): >
- **savia-setup** (cmd): >
- **savia-shield** (cmd): Gestión de Savia Shield: activar, desactivar y comprobar instalación del sistema de soberanía de datos. Desactivado por defecto.
- **savia-shield-setup** (script): savia-shield-setup.sh — Instalador de Savia Shield
- **savia-sprint** (cmd): >
- **savia-status** (cmd): Show Savia current status, health metrics, and top pending priorities
- **savia-status** (script): savia-status.sh — What is Savia doing right now?
- **savia-team** (cmd): >
- **savia-timesheet** (cmd): >
- **savia-travel** (script): savia-travel.sh — Travel Mode Core (≤150 lines)
- **savia-travel-init** (cmd): >
- **savia-travel-init** (script): savia-init.sh — Travel Mode Init Script (template)
- **savia-travel-ops** (script): savia-travel-ops.sh — Pack and init operations for savia-travel.sh
- **savia-travel-pack** (cmd): >
- **savia-voice-chunk** (script): savia-voice-chunk.sh — SE-075 Slice 2.
- **savia-watch** (script): savia-watch.sh — Live activity feed from Savia
- **savia-watchdog** (script): savia-watchdog.sh — Emergency fallback: detect internet loss, activate local LLM
- **slack-search** (cmd): >
- **voice-inbox** (skill): Transcripción de audio y flujo audio→texto→acción para mensajes de voz
- **word-digest** (agent): >
- **zeroclaw-meeting** (cmd): Live meeting transcription via ZeroClaw — speaker diarization, voice identification, and digest.
