# quality — Savia Capability Map (L1)
> 227 resources

- **/a11y-audit** (cmd): Auditoría de accesibilidad WCAG 2.2 completa con escaneo de HTML/componentes. Detecta: alt text faltante, problemas de contraste, navegación por teclado, etiquetas ARIA, gestión de focus, jerarquía de encabezados, etiquetas de formularios.
- **/a11y-fix** (cmd): Correcciones automáticas de accesibilidad con verificación y preview. Genera código de fix para issues detectados por /a11y-audit. Preview antes de aplicar. Verifica que no introduce nuevos problemas. Covers: alt text, ARIA attributes, focu
- **/drift-check** (cmd): Audita reglas CLAUDE.md vs. estado real del repo. Detecta divergencias, archivos huérfanos, tests faltantes y patrones de PII.
- **Court Review** (cmd): Convene the Code Review Court to evaluate implementation quality across 6 judges
- **adversarial-security** (skill): Pipeline de seguridad adversarial — Red Team, Blue Team, Auditor con scoring
- **ai-audit-log** (cmd): Log de auditoría IA — quién ejecutó qué agente, sobre qué datos, cuándo
- **ai-exposure-audit** (cmd): Auditoría de exposición IA por rol — observed exposure, riesgo de desplazamiento, reskilling
- **ai-labor-impact** (skill): AI labor impact analysis — exposure audit, reskilling plans, workforce forecasting
- **android-autonomous-debugger** (skill): Autonomous debugging and testing of Android apps against physical devices via USB/ADB
- **architectural-vocabulary-audit** (script): architectural-vocabulary-audit.sh — SE-082 Slice única.
- **architecture-judge** (agent): Code Review Court judge — boundaries, coupling, layer violations, patterns
- **ast-comprehension** (skill): Comprensión estructural de código que no hemos escrito. Queries tipadas (impl, callers, tests, grep-code, peek, symbols) en lugar de leer ficheros completos. Inspirado en el patrón RLM (Recursive Language Models, Zhang/Kraska/Khattab 2025).
- **audit** (cmd): Generate professional executive audit report for workspace reliability assessment
- **banking-data-governance** (cmd): Auditar gobierno de datos — lineage, clasificación, GDPR/LOPD, feature stores
- **banking-mlops-audit** (cmd): Auditar pipeline MLOps — versionado, drift, XAI, model risk, scoring architectures
- **case-review** (cmd): Generate benefit realization review at 90/180/365 days
- **ci-test-quality-gate** (script): ci-test-quality-gate.sh — CI gate: test quality + coverage
- **cognitive-judge** (agent): Code Review Court judge — debuggability at 3AM, naming, complexity, logs
- **comprehension-audit** (cmd): Scan recent implementations and identify which lack comprehension reports. Report coverage and recommendations.
- **confidentiality-auditor** (agent): Audita cumplimiento de confidencialidad en PRs de pm-workspace (repo publico). Descubre dinamicamente datos sensibles del workspace y verifica que no se filtran en el diff. Genera veredicto CLEAN/BLOCKED con firma si pasa.
- **confidentiality-check** (cmd): Auditoria pre-PR de confidencialidad y firma criptografica
- **confidentiality-sign** (script): confidentiality-sign.sh — Cryptographic signature for confidentiality audit
- **consensus-validation** (skill): Orquestación de 4-judge panel (reflection, code-review, business, performance)
- **correctness-judge** (agent): Code Review Court judge — logic, tests, edge cases, error paths
- **court-orchestrator** (agent): Convenes the Code Review Court, manages fix cycles, produces .review.crc
- **court-review** (script): court-review.sh — Code Review Court orchestration helper
- **coverage-report** (script): coverage-report.sh — Generate test coverage report for pm-workspace
- **dependencies-audit** (cmd): >
- **docs-quality-audit** (cmd): Auditar calidad de documentacion basada en feedback de agentes
- **drift-auditor** (agent): Auditoría de convergencia repo: detecta drift entre docs, config y código. Usar PROACTIVELY tras cambios grandes o al inicio de sprint.
- **executive-audit** (script): executive-audit.sh — Executive Audit for PM Workspace
- **expertise-asymmetry-judge** (agent): Recommendation Tribunal judge — when draft falls in a domain the active user marks as `audit_level: blind`, force a rewrite with explanation/alternatives/verification
- **fix-assigner** (agent): Creates fix tasks from Court findings, assigns to dev agents, triggers re-review
- **frontend-test-runner** (agent): Post-commit frontend test execution — unit, component, e2e, coverage
- **grill-me** (skill): Adversarial review that hunts every weakness, assumption, edge case, and missing test. Opponent mode — finds what will break before it breaks in production. Use when merging, when reviewing security-critical code, or when the solution feels
- **hook-event-gap-audit** (script): hook-event-gap-audit.sh — Audita los 11 eventos de hook no cubiertos en pm-workspace
- **hook-injection-audit** (script): hook-injection-audit.sh — SE-060 Slice 1 hook injection patterns audit.
- **hook-latency-audit** (script): hook-latency-audit.sh — SE-037 Slice 1 hook latency enforcement audit.
- **hook-test-coverage-audit** (script): hook-test-coverage-audit.sh — Detect hooks in .opencode/hooks/ without BATS tests.
- **hub-audit** (cmd): Auditar dependencias entre reglas de dominio, comandos y agentes — recalcular el índice de hubs
- **knowledge-lint** (cmd): Health check for the persistent knowledge base — detect orphans, stale refs, missing evidence
- **knowledge-lint** (script): knowledge-lint.sh — LLM Wiki pattern: periodic knowledge base health check
- **legal-audit** (cmd): Auditoría de compliance legal contra legislación española (legalize-es)
- **legal-compliance** (skill): Auditoría de compliance legal contra legislación española consolidada (legalize-es)
- **markdownlint** (script): Native markdownlint wrapper — no npm dependency.
- **mcp-audit** (script): mcp-audit.sh — audit MCP server token overhead across configs
- **mcp-security-audit** (script): mcp-security-audit.sh — SE-058 Slice 1 MCP supply-chain + config audit.
- **model-upgrade-audit** (cmd): Audit workspace components for prompt debt that newer models may not need
- **model-upgrade-audit** (skill): Audit workspace components for prompt debt when a new model is available. Detect workarounds, propose simplifications, compare with evals.
- **model-upgrade-auditor** (agent): Audits agents, skills, and prompts for workarounds that newer models may no longer need. Proposes simplifications with eval-backed evidence.
- **mutation-audit** (skill): Mutation testing — mide calidad real de tests, detecta zombies AI-generated. On-demand sobre módulo concreto. Invocable.
- **mutation-audit** (script): mutation-audit.sh — SE-035 Slice 1 mutation testing audit.
- **opencode-cross-audit** (script): opencode-cross-audit.sh — Verifies .opencode/ vs .claude/ resource alignment
- **opencode-parity-audit** (script): opencode-parity-audit.sh — SE-077 Slice 2
- **overnight-sprint** (cmd): Launch autonomous overnight sprint — executes low-risk tasks, creates PRs for human review
- **pentester** (agent): >
- **pentesting** (skill): Arsenal de pentesting con pipeline Shannon — queue-driven, proof-based, 5 fases paralelas
- **perf-audit** (cmd): Auditoría estática de rendimiento — detecta hotspots, async anti-patterns y funciones pesadas
- **perf-fix** (cmd): Optimización test-first de hallazgos de rendimiento — crea tests si no existen, aplica fix, re-verifica
- **perf-report** (cmd): Informe ejecutivo de rendimiento — hotspots, async issues, roadmap y tendencias
- **performance-audit** (skill): Auditoría estática de rendimiento — detección de hotspots, async anti-patterns, test-first optimization
- **permissions-wildcard-audit** (script): permissions-wildcard-audit.sh — SE-059 Slice 1 permissions wildcard audit.
- **postmortem-review** (cmd): Review and learn from past incident postmortems
- **pr-agent-judge** (skill): 5º juez del Court — wrapper sobre qodo-ai/pr-agent OSS. Ejecuta review/describe/improve contra un PR y devuelve JSON compatible con Court.
- **pr-agent-judge** (agent): External 5th judge of the Code Review Court — wraps qodo-ai/pr-agent OSS (SPEC-124). Opt-in via COURT_INCLUDE_PR_AGENT=true.
- **pr-agent-run** (script): pr-agent-run.sh — SPEC-124
- **pr-context-loader** (script): pr-context-loader.sh — SPEC-022 F4: Load project context before PR creation
- **pr-digest** (cmd): Digestión contextual de un PR para revisión rápida. Analiza impacto, riesgos y genera resumen ejecutivo en español.
- **pr-pending** (cmd): >
- **pr-plan** (cmd): Pre-flight checklist: 15 gates (G0-G14) before push/PR. Prevents CI failures.
- **pr-plan** (script): pr-plan.sh — 10-gate pre-flight + sign + push + PR
- **pr-plan-gates** (script): pr-plan-gates.sh — Gate functions for pr-plan.sh (sourced, not executed)
- **pr-plan-queue-check** (script): pr-plan-queue-check.sh — SPEC-SE-012 Module 4.
- **pr-rebase** (script): pr-rebase.sh — Rebase current PR branch onto origin/main and re-sign.
- **pr-review** (cmd): >
- **prompt-security-scan** (script): prompt-security-scan.sh — Static analyzer for prompt injection/leakage
- **python-sbom** (script): python-sbom.sh — SE-056 Slice 1 Python SBOM + requirements audit.
- **qa-bug-triage** (cmd): Triage asistido de bugs — clasificación, duplicados, asignación sugerida
- **qa-dashboard** (cmd): Dashboard de calidad — cobertura, tests flaky, bugs, escape rate, trends
- **qa-regression-plan** (cmd): Plan de regresión basado en ficheros cambiados — impacto de cambios y suites a ejecutar
- **qa-wizard** (cmd): Interactive wizard for QA engineer onboarding
- **rbac-management** (skill): Role management skill — grant, revoke, audit, and verify user permissions
- **rbac-manager** (cmd): Role-based access control — grant, revoke, audit roles and permissions
- **record-start** (cmd): Start recording session for audit and replay
- **ref-resolve** (cmd): Resolve and preview resource references
- **release-readiness** (cmd): Checklist de release — features, tests, docs, compliance, deployment
- **repos-pr-review** (cmd): >
- **review-cache** (script): review-cache.sh - Gestión de caché de code review
- **review-cache-clear** (cmd): Limpiar la caché de code review
- **review-cache-stats** (cmd): Estadísticas de la caché de code review
- **review-community** (cmd): Revisar PRs, issues y contribuciones de la comunidad (protocolo privado de maintainer)
- **review-community** (script): review-community.sh — Revisión de PRs/issues de la comunidad (LOCAL ONLY)
- **review-depth-selector** (script): review-depth-selector.sh — Select review depth based on risk score
- **rule-orphan-detector** (script): rule-orphan-detector.sh — SE-048 Slice 1 rule usage audit.
- **scheduled-test** (cmd): Enviar test message para verificar integración de plataforma de notificaciones
- **security-alerts** (cmd): >
- **security-attacker** (agent): >
- **security-audit** (cmd): >
- **security-audit-all** (script): security-audit-all.sh — Unified runner for all security scanners.
- **security-auditor** (agent): >
- **security-auto-remediation** (cmd): >
- **security-defender** (agent): >
- **security-guardian** (agent): >
- **security-judge** (agent): Code Review Court judge — OWASP, PII, injection, auth, credentials
- **security-pipeline** (cmd): >
- **security-review** (cmd): >
- **security-scan** (script): security-scan.sh — Security audit for pm-workspace
- **skill-audit** (script): skill-audit.sh — Baseline skill catalog quality auditor (SE-084 Slice 1)
- **skill-catalog-audit** (script): skill-catalog-audit.sh — SE-084 Slice 1.
- **skills-usage-audit** (script): skills-usage-audit.sh — Audita uso de los 91 skills de pm-workspace.
- **sovereignty-audit** (cmd): Cognitive sovereignty audit — diagnose AI vendor lock-in risk and data portability
- **sovereignty-auditor** (skill): Auditoría de soberanía cognitiva — diagnóstico de lock-in de IA
- **spellcheck-docs** (script): spellcheck-docs.sh — Orthographic review using accent dictionaries
- **tdd-vertical-slices** (skill): Test-driven development with vertical-slice red-green-refactor cycles. Use when applying TDD to a new feature or bug fix, when user mentions 'red-green-refactor', 'tdd', 'test-first', 'vertical slice' — explicitly avoids the 'horizontal sli
- **test-accessibility** (script): test-accessibility.sh — Validates accessibility universal feature files
- **test-ai-adoption** (script): ── test-ai-adoption.sh ────────────────────────────────────────────────────────
- **test-ai-governance** (script): ── test-ai-governance.sh ─────────────────────────────────────────────────────
- **test-ai-labor-impact** (script): test-ai-labor-impact.sh — Tests for AI Labor Impact Analysis (v2.5.0)
- **test-ai-planning** (script): ── test-ai-planning.sh ────────────────────────────────────────────────
- **test-ai-safety** (script): ── test-ai-safety.sh ────────────────────────────────────────────────────────
- **test-architect** (skill): Design and generate highest-quality tests across 16 languages and 14 test types
- **test-architect** (agent): >
- **test-architecture-debt** (script): Test: Architecture & Debt v0.71.0 (Era 13)
- **test-auditor** (script): test-auditor.sh — Score, validate, and certify BATS test files
- **test-auditor-sweep** (script): test-auditor-sweep.sh — SE-039 Slice 1 global BATS test audit sweep.
- **test-backlog-git** (script): test-backlog-git.sh — Structural tests for BacklogGit (Era 32 — v2.7.0)
- **test-backlog-intelligence** (script): ── test-backlog-intelligence.sh ──────────────────────────────────────────────
- **test-backup** (script): test-backup.sh — Tests del sistema de backup cifrado
- **test-banking-vertical** (script): Test: v0.73.0 — Vertical Banking
- **test-ceo-reports** (script): ── test-ceo-reports.sh ───────────────────────────────────────────────────
- **test-ceremony-intelligence** (script): ── test-ceremony-intelligence.sh ────────────────────────────────────────────
- **test-client-profiles** (script): test-client-profiles.sh — Structural tests for Client Profiles (Era 31 — v2.6.0)
- **test-coherence-validator** (script): Test suite for Output Coherence Validator — Quality Validation Framework
- **test-company-profile** (script): ── test-company-profile.sh ──────────────────────────────────────────────────
- **test-company-repo** (script): test-company-repo.sh — Tests for Company Savia branch-based architecture
- **test-confidence-calibration** (script): Test suite for Confidence Calibration — Quality Validation Framework
- **test-consensus** (script): Test suite for Multi-Judge Consensus — Quality Validation Framework
- **test-context-aging** (script): ── test-context-aging.sh ──────────────────────────────────────────────────
- **test-context-eng-improvements** (script): test-context-eng-improvements.sh — Tests para Context Engineering Improvements
- **test-context-engineering** (script): Test Suite for Context Engineering 2.0 Commands (v0.62.0)
- **test-context-interview** (script): test-context-interview.sh — Structural tests for Context Interview (Era 33 — v2.8.0)
- **test-context-optimization** (script): Test: Context Optimization v0.71.0 (Era 13)
- **test-context-tracking** (script): ── test-context-tracking.sh ───────────────────────────────────────────────
- **test-contribute** (script): test-contribute.sh — Tests del sistema de comunidad y contribución
- **test-cost-center** (script): ── Test: cost-center (Era 38 — Cost Management & Billing) ──
- **test-coverage-checker** (script): test-coverage-checker.sh — Verify every script has a corresponding test
- **test-cross-project** (script): ── test-cross-project.sh ────────────────────────────────────────────────
- **test-dev-productivity** (script): ── test-dev-productivity.sh ──────────────────────────────────────────────
- **test-docs-overhaul** (script): test-docs-overhaul.sh — Tests para Documentation Overhaul (Savia-led)
- **test-engineer** (agent): >
- **test-enterprise-dashboard** (script): ── Test: enterprise-dashboard (Era 41 — Enterprise Reporting & Analytics) ──
- **test-equality-shield** (script): test-equality-shield.sh — Tests for Equality Shield (v2.1.0)
- **test-era18-commands** (script): ── test-era18-commands.sh — Era 18 command structure validation ──
- **test-era18-formulas** (script): ── test-era18-formulas.sh — Scoring/formula correctness ──
- **test-era18-rules** (script): ── test-era18-rules.sh — Era 18 rule/config validation ──
- **test-evolving-playbooks** (script): Test Suite: Evolving Playbooks (ACE) — v0.63.0
- **test-frontend-testing** (script): test-frontend-testing.sh — Tests for Frontend Testing Nueva Era
- **test-governance** (script): Test: Governance v0.71.0 (Era 13)
- **test-governance-enterprise** (script): ── Test: governance-enterprise (Era 40 — Governance & Audit Trail) ──
- **test-hub-audit** (script): ── test-hub-audit.sh ─────────────────────────────────────────────────────
- **test-install** (script): test-install.sh — Structural validation for pm-workspace installers
- **test-integration-company** (script): test-integration-company.sh — Integration orchestrator for Savia v3
- **test-integration-hub** (script): ── test-integration-hub.sh ─────────────────────────────────────────────────
- **test-integrations-external** (script): Test: Integrations External v0.71.0 (Era 13)
- **test-memory-improvements** (script): Test suite for Memory Store Improvements v1.9.0
- **test-multi-layer-caching** (script): Test: Multi-Layer Caching — v0.65.0
- **test-multi-platform** (script): ── test-multi-platform.sh ──────────────────────────────────────────────────
- **test-multi-tenant** (script): Test Suite: v0.70.0 Multi-Tenant & Skills Marketplace
- **test-nl-resolution** (script): Test suite for NL Command Resolution v1.9.0
- **test-observability-core** (script): Test: Observability Core v0.71.0 (Era 13)
- **test-okr-strategy** (script): ── test-okr-strategy.sh ──────────────────────────────────────────────────────
- **test-onboard-enterprise** (script): ── Test: onboard-enterprise (Era 39 — Onboarding at Scale) ──
- **test-orgchart-diagrams** (script): ============================================================================
- **test-pbi-history** (script): test-pbi-history.sh — Validates PBI Field-Level History implementation
- **test-pbi-spec-links** (script): test-pbi-spec-links.sh — Tests for PBI ↔ Spec bidirectional linkage
- **test-performance-quality** (script): Test: Performance & Quality v0.71.0 (Era 13)
- **test-pipeline-devops** (script): Test: Pipeline & DevOps v0.71.0 (Era 13)
- **test-playbooks** (script): Test: Playbooks v0.71.0 (Era 13)
- **test-po-analytics** (script): ── test-po-analytics.sh ─────────────────────────────────────────────────
- **test-profile-system** (script): ── test-profile-system.sh ─────────────────────────────────────────────────
- **test-project-management** (script): Test: Project Management v0.71.0 (Era 13)
- **test-qa-toolkit** (script): ── test-qa-toolkit.sh ────────────────────────────────────────────────────
- **test-rbac-manager** (script): ── Test: rbac-manager (Era 37 — RBAC File-Based) ──
- **test-reflection-validator** (script): Test suite for Reflection Validator — System 2 Meta-Cognition Agent
- **test-repo-management** (script): Test: Repo Management v0.71.0 (Era 13)
- **test-review-community** (script): test-review-community.sh — Tests del protocolo de revisión comunitaria
- **test-runner** (agent): >
- **test-savia-confidentiality** (script): test-savia-confidentiality.sh — E2E encrypted messaging confidentiality
- **test-savia-crypto** (script): test-savia-crypto.sh — Tests for RSA+AES encryption
- **test-savia-flow** (script): test-savia-flow.sh — Tests for Savia Flow on branch-based architecture (~25 tests)
- **test-savia-flow-tasks** (script): test-savia-flow-tasks.sh — Git-native task tests via savia-branch.sh
- **test-savia-hub** (script): test-savia-hub.sh — Structural tests for SaviaHub (Era 30)
- **test-savia-index** (script): test-savia-index.sh — Tests for indexes on branch-based architecture
- **test-savia-messaging** (script): test-savia-messaging.sh — Tests for savia branch-based messaging infrastructure
- **test-savia-school** (script): test-savia-school.sh — Tests for Savia School educational vertical
- **test-savia-travel** (script): test-savia-travel.sh — Tests for Travel Mode (pack/unpack/verify/clean)
- **test-scale-optimizer** (script): ── Test: scale-optimizer (Era 42 — Scale & Integration Polish) ──
- **test-scoring-intelligence** (script): test-scoring-intelligence.sh — Tests for Scoring Intelligence (v2.3.0)
- **test-security-compliance** (script): Test: Security & Compliance v0.71.0 (Era 13)
- **test-semantic-memory** (script): Test suite for Semantic Memory 2.0 v0.64.0
- **test-sovereignty-audit** (script): test-sovereignty-audit.sh — Structural tests for Cognitive Sovereignty (Era 35 — v2.10.0)
- **test-specs-sdd** (script): Test: Specs & SDD v0.71.0 (Era 13)
- **test-stress-hooks** (script): ── test-stress-hooks.sh — Stress tests for all hooks ──
- **test-stress-runner** (script): ── test-stress-runner.sh — Orchestrator for all stress tests ──
- **test-stress-scripts** (script): ── test-stress-scripts.sh — Robustness of supporting scripts ──
- **test-stress-security** (script): ── test-stress-security.sh — Security pattern coverage (SEC-1 to SEC-9) ──
- **test-tasks-entities** (script): test-tasks-entities.sh — Validate Tasks as First-Class Entities
- **test-team-orchestrator** (script): ── Test: team-orchestrator (Era 36 — Multi-Team Coordination) ──
- **test-tech-lead** (script): ── test-tech-lead.sh ─────────────────────────────────────────────────────
- **test-update-system** (script): test-update-system.sh — Tests del sistema de actualización de pm-workspace
- **test-utils** (script): test-utils.sh — Funciones compartidas para todos los test scripts
- **test-vertical-compliance** (script): ── test-vertical-compliance.sh ────────────────────────────────────────────────
- **test-vertical-detection** (script): test-vertical-detection.sh — Tests del sistema de detección de verticales
- **test-verticals** (script): Test: Verticals v0.71.0 (Era 13)
- **test-wellbeing-guardian** (script): test-wellbeing-guardian.sh — Structural tests for Wellbeing Guardian (Era 34 — v2.9.0)
- **test-workspace** (script): ============================================================================
- **testplan-generate** (cmd): Generación de plan de pruebas desde specs SDD o PBIs
- **testplan-results** (cmd): >
- **testplan-status** (cmd): >
- **verification-lattice** (skill): Multi-layer verification pipeline beyond Code Review
- **visual-digest** (agent): Digestión de imágenes con OCR contextual — 5 pasadas. Fotos de pizarras, notas manuscritas, diagramas en papel, capturas de reuniones. Usa contexto REAL del proyecto para resolver ambigüedades. PROACTIVELY cuando se detectan imágenes en car
- **visual-qa** (cmd): Visual quality assurance via screenshot analysis. Analyze UI screenshots against design specs and reference images using vision capabilities.
- **visual-qa-agent** (agent): Visual QA: screenshot analysis, wireframe comparison, regression detection. Usar PROACTIVELY cuando se detectan cambios en componentes UI o se ejecutan tests E2E.
- **visual-regression** (cmd): Automated visual regression testing across builds and branches. Detect visual regressions with baseline comparison and approval workflows.
- **web-e2e-tester** (agent): Autonomous E2E testing of web apps against live instances. Use PROACTIVELY when: deploying savia-web, after UI changes, or running regression tests. Equivalent of android-autonomous-debugger for web.
- **workspace-integrity** (skill): Catalogo de integrity auditors — drift CLAUDE.md, rule manifest, orphan rules, agents catalog sync, baseline, agent size
- **zeroclaw** (cmd): Interface with ZeroClaw ESP32 — setup, test, send commands, flash firmware.
